// =============================================
// Tibia-Style Game - Item Definitions
// =============================================

import { ItemDefinition, ItemType, Rarity, Vocation } from './types';

export const ITEMS: Record<string, ItemDefinition> = {
  // === CONSUMABLES ===
  health_potion_small: {
    id: 'health_potion_small',
    name: 'Small Health Potion',
    type: ItemType.CONSUMABLE,
    rarity: Rarity.COMMON,
    description: 'Restores 50 HP',
    weight: 0.5,
    healAmount: 50,
    levelReq: 1,
    stackable: true,
    sellPrice: 5,
    buyPrice: 10,
    color: '#ff4444',
    icon: '🧪',
  },
  health_potion_medium: {
    id: 'health_potion_medium',
    name: 'Medium Health Potion',
    type: ItemType.CONSUMABLE,
    rarity: Rarity.UNCOMMON,
    description: 'Restores 150 HP',
    weight: 0.7,
    healAmount: 150,
    levelReq: 5,
    stackable: true,
    sellPrice: 20,
    buyPrice: 40,
    color: '#ff2222',
    icon: '🧪',
  },
  health_potion_large: {
    id: 'health_potion_large',
    name: 'Large Health Potion',
    type: ItemType.CONSUMABLE,
    rarity: Rarity.RARE,
    description: 'Restores 400 HP',
    weight: 1.0,
    healAmount: 400,
    levelReq: 15,
    stackable: true,
    sellPrice: 80,
    buyPrice: 150,
    color: '#cc0000',
    icon: '🧪',
  },
  mana_potion_small: {
    id: 'mana_potion_small',
    name: 'Small Mana Potion',
    type: ItemType.CONSUMABLE,
    rarity: Rarity.COMMON,
    description: 'Restores 50 MP',
    weight: 0.5,
    manaAmount: 50,
    levelReq: 1,
    stackable: true,
    sellPrice: 5,
    buyPrice: 10,
    color: '#4444ff',
    icon: '🧪',
  },
  mana_potion_medium: {
    id: 'mana_potion_medium',
    name: 'Medium Mana Potion',
    type: ItemType.CONSUMABLE,
    rarity: Rarity.UNCOMMON,
    description: 'Restores 150 MP',
    weight: 0.7,
    manaAmount: 150,
    levelReq: 5,
    stackable: true,
    sellPrice: 20,
    buyPrice: 40,
    color: '#2222ff',
    icon: '🧪',
  },
  mana_potion_large: {
    id: 'mana_potion_large',
    name: 'Large Mana Potion',
    type: ItemType.CONSUMABLE,
    rarity: Rarity.RARE,
    description: 'Restores 400 MP',
    weight: 1.0,
    manaAmount: 400,
    levelReq: 15,
    stackable: true,
    sellPrice: 80,
    buyPrice: 150,
    color: '#0000cc',
    icon: '🧪',
  },

  // === WEAPONS ===
  wooden_sword: {
    id: 'wooden_sword',
    name: 'Wooden Sword',
    type: ItemType.WEAPON,
    rarity: Rarity.COMMON,
    description: 'A simple wooden sword.',
    weight: 3.0,
    attack: 5,
    levelReq: 1,
    stackable: false,
    sellPrice: 10,
    buyPrice: 20,
    color: '#a0784c',
    icon: '🗡️',
  },
  short_sword: {
    id: 'short_sword',
    name: 'Short Sword',
    type: ItemType.WEAPON,
    rarity: Rarity.COMMON,
    description: 'A basic iron sword.',
    weight: 4.0,
    attack: 10,
    levelReq: 3,
    stackable: false,
    sellPrice: 30,
    buyPrice: 60,
    color: '#b0b0b0',
    icon: '⚔️',
  },
  long_sword: {
    id: 'long_sword',
    name: 'Long Sword',
    type: ItemType.WEAPON,
    rarity: Rarity.UNCOMMON,
    description: 'A well-crafted long sword.',
    weight: 5.5,
    attack: 18,
    levelReq: 8,
    vocationReq: [Vocation.KNIGHT, Vocation.PALADIN],
    stackable: false,
    sellPrice: 100,
    buyPrice: 200,
    color: '#c0c0c0',
    icon: '⚔️',
  },
  battle_axe: {
    id: 'battle_axe',
    name: 'Battle Axe',
    type: ItemType.WEAPON,
    rarity: Rarity.UNCOMMON,
    description: 'A heavy but powerful axe.',
    weight: 7.0,
    attack: 25,
    levelReq: 12,
    vocationReq: [Vocation.KNIGHT],
    stackable: false,
    sellPrice: 200,
    buyPrice: 400,
    color: '#888888',
    icon: '🪓',
  },
  magic_staff: {
    id: 'magic_staff',
    name: 'Magic Staff',
    type: ItemType.WEAPON,
    rarity: Rarity.UNCOMMON,
    description: 'A staff imbued with magical energy.',
    weight: 3.0,
    magicAttack: 20,
    levelReq: 5,
    vocationReq: [Vocation.SORCERER, Vocation.DRUID],
    stackable: false,
    sellPrice: 120,
    buyPrice: 250,
    color: '#9b59b6',
    icon: '🪄',
  },
  dragon_sword: {
    id: 'dragon_sword',
    name: 'Dragon Sword',
    type: ItemType.WEAPON,
    rarity: Rarity.EPIC,
    description: 'A legendary sword forged in dragon fire.',
    weight: 6.0,
    attack: 40,
    magicAttack: 10,
    levelReq: 25,
    vocationReq: [Vocation.KNIGHT],
    stackable: false,
    sellPrice: 500,
    buyPrice: 1000,
    color: '#e74c3c',
    icon: '⚔️',
  },
  crossbow: {
    id: 'crossbow',
    name: 'Crossbow',
    type: ItemType.WEAPON,
    rarity: Rarity.UNCOMMON,
    description: 'A powerful ranged weapon.',
    weight: 5.0,
    attack: 15,
    levelReq: 8,
    vocationReq: [Vocation.PALADIN],
    stackable: false,
    sellPrice: 150,
    buyPrice: 300,
    color: '#8B4513',
    icon: '🏹',
  },

  // === ARMOR ===
  leather_armor: {
    id: 'leather_armor',
    name: 'Leather Armor',
    type: ItemType.ARMOR,
    rarity: Rarity.COMMON,
    description: 'Basic leather protection.',
    weight: 5.0,
    defense: 5,
    levelReq: 1,
    stackable: false,
    sellPrice: 15,
    buyPrice: 30,
    color: '#8B4513',
    icon: '🦺',
  },
  chain_mail: {
    id: 'chain_mail',
    name: 'Chain Mail',
    type: ItemType.ARMOR,
    rarity: Rarity.UNCOMMON,
    description: 'Interlocking metal rings provide good protection.',
    weight: 10.0,
    defense: 15,
    levelReq: 8,
    stackable: false,
    sellPrice: 150,
    buyPrice: 300,
    color: '#a0a0a0',
    icon: '🛡️',
  },
  plate_armor: {
    id: 'plate_armor',
    name: 'Plate Armor',
    type: ItemType.ARMOR,
    rarity: Rarity.RARE,
    description: 'Heavy steel plates offer excellent protection.',
    weight: 18.0,
    defense: 30,
    levelReq: 18,
    vocationReq: [Vocation.KNIGHT, Vocation.PALADIN],
    stackable: false,
    sellPrice: 400,
    buyPrice: 800,
    color: '#d0d0d0',
    icon: '🛡️',
  },
  mage_robe: {
    id: 'mage_robe',
    name: 'Mage Robe',
    type: ItemType.ARMOR,
    rarity: Rarity.UNCOMMON,
    description: 'A robe enchanted with protective magic.',
    weight: 3.0,
    defense: 5,
    magicDefense: 15,
    levelReq: 5,
    vocationReq: [Vocation.SORCERER, Vocation.DRUID],
    stackable: false,
    sellPrice: 120,
    buyPrice: 250,
    color: '#6c3483',
    icon: '🧥',
  },

  // === SHIELDS ===
  wooden_shield: {
    id: 'wooden_shield',
    name: 'Wooden Shield',
    type: ItemType.SHIELD,
    rarity: Rarity.COMMON,
    description: 'A simple wooden shield.',
    weight: 4.0,
    defense: 4,
    levelReq: 1,
    stackable: false,
    sellPrice: 10,
    buyPrice: 20,
    color: '#a0784c',
    icon: '🛡️',
  },
  iron_shield: {
    id: 'iron_shield',
    name: 'Iron Shield',
    type: ItemType.SHIELD,
    rarity: Rarity.UNCOMMON,
    description: 'A sturdy iron shield.',
    weight: 8.0,
    defense: 12,
    levelReq: 8,
    vocationReq: [Vocation.KNIGHT, Vocation.PALADIN],
    stackable: false,
    sellPrice: 100,
    buyPrice: 200,
    color: '#808080',
    icon: '🛡️',
  },
  tower_shield: {
    id: 'tower_shield',
    name: 'Tower Shield',
    type: ItemType.SHIELD,
    rarity: Rarity.RARE,
    description: 'A massive shield that provides great protection.',
    weight: 15.0,
    defense: 25,
    levelReq: 20,
    vocationReq: [Vocation.KNIGHT],
    stackable: false,
    sellPrice: 350,
    buyPrice: 700,
    color: '#b0b0b0',
    icon: '🛡️',
  },

  // === HELMETS ===
  leather_helmet: {
    id: 'leather_helmet',
    name: 'Leather Helmet',
    type: ItemType.HELMET,
    rarity: Rarity.COMMON,
    description: 'A simple leather cap.',
    weight: 2.0,
    defense: 2,
    levelReq: 1,
    stackable: false,
    sellPrice: 5,
    buyPrice: 10,
    color: '#a0784c',
    icon: '⛑️',
  },
  iron_helmet: {
    id: 'iron_helmet',
    name: 'Iron Helmet',
    type: ItemType.HELMET,
    rarity: Rarity.UNCOMMON,
    description: 'A solid iron helmet.',
    weight: 5.0,
    defense: 8,
    levelReq: 8,
    stackable: false,
    sellPrice: 60,
    buyPrice: 120,
    color: '#808080',
    icon: '⛑️',
  },
  crown_helmet: {
    id: 'crown_helmet',
    name: 'Crown Helmet',
    type: ItemType.HELMET,
    rarity: Rarity.RARE,
    description: 'A regal helmet fit for royalty.',
    weight: 4.0,
    defense: 12,
    magicDefense: 5,
    levelReq: 20,
    stackable: false,
    sellPrice: 300,
    buyPrice: 600,
    color: '#ffd700',
    icon: '👑',
  },

  // === LEGS ===
  leather_legs: {
    id: 'leather_legs',
    name: 'Leather Legs',
    type: ItemType.LEGS,
    rarity: Rarity.COMMON,
    description: 'Basic leather leggings.',
    weight: 3.0,
    defense: 3,
    levelReq: 1,
    stackable: false,
    sellPrice: 8,
    buyPrice: 15,
    color: '#8B4513',
    icon: '👖',
  },
  chain_legs: {
    id: 'chain_legs',
    name: 'Chain Legs',
    type: ItemType.LEGS,
    rarity: Rarity.UNCOMMON,
    description: 'Chain mail leggings.',
    weight: 6.0,
    defense: 8,
    levelReq: 8,
    stackable: false,
    sellPrice: 80,
    buyPrice: 160,
    color: '#a0a0a0',
    icon: '👖',
  },

  // === BOOTS ===
  leather_boots: {
    id: 'leather_boots',
    name: 'Leather Boots',
    type: ItemType.BOOTS,
    rarity: Rarity.COMMON,
    description: 'Simple leather boots.',
    weight: 2.0,
    defense: 1,
    levelReq: 1,
    stackable: false,
    sellPrice: 5,
    buyPrice: 10,
    color: '#8B4513',
    icon: '👢',
  },
  steel_boots: {
    id: 'steel_boots',
    name: 'Steel Boots',
    type: ItemType.BOOTS,
    rarity: Rarity.UNCOMMON,
    description: 'Sturdy steel boots.',
    weight: 5.0,
    defense: 4,
    levelReq: 10,
    stackable: false,
    sellPrice: 100,
    buyPrice: 200,
    color: '#c0c0c0',
    icon: '👢',
  },

  // === RINGS ===
  ring_of_life: {
    id: 'ring_of_life',
    name: 'Ring of Life',
    type: ItemType.RING,
    rarity: Rarity.RARE,
    description: 'Slowly regenerates health.',
    weight: 0.1,
    defense: 3,
    levelReq: 10,
    stackable: false,
    sellPrice: 200,
    buyPrice: 400,
    color: '#ff0000',
    icon: '💍',
  },
  ring_of_mana: {
    id: 'ring_of_mana',
    name: 'Ring of Mana',
    type: ItemType.RING,
    rarity: Rarity.RARE,
    description: 'Increases mana regeneration.',
    weight: 0.1,
    magicDefense: 5,
    levelReq: 10,
    vocationReq: [Vocation.SORCERER, Vocation.DRUID],
    stackable: false,
    sellPrice: 200,
    buyPrice: 400,
    color: '#0000ff',
    icon: '💍',
  },

  // === GOLD ===
  gold_coin: {
    id: 'gold_coin',
    name: 'Gold Coin',
    type: ItemType.GOLD,
    rarity: Rarity.COMMON,
    description: 'Shiny gold coin.',
    weight: 0.01,
    levelReq: 1,
    stackable: true,
    sellPrice: 1,
    buyPrice: 0,
    color: '#ffd700',
    icon: '🪙',
  },
};

export function getItem(id: string): ItemDefinition | undefined {
  return ITEMS[id];
}

export function getShopItems(shopItemIds: string[]): ItemDefinition[] {
  return shopItemIds.map(id => ITEMS[id]).filter(Boolean) as ItemDefinition[];
}