// =============================================
// Tibia-Style Game - Item Definitions
// =============================================

import { ItemDefinition, ItemType, Rarity, Vocation } from './types';

export const ITEMS: Record<string, ItemDefinition> = {
    // === NEW LOOTS ===
  meat: {
    id: 'meat',
    name: 'Meat',
    type: ItemType.CONSUMABLE,
    rarity: Rarity.COMMON,
    description: 'Fresh meat. Restores 30 HP over time.',
    weight: 2.0,
    healAmount: 30,
    levelReq: 1,
    stackable: true,
    sellPrice: 2,
    buyPrice: 5,
    color: '#c0392b',
    icon: '🍖',
  },
  crystal_wand: {
    id: 'crystal_wand',
    name: 'Crystal Wand',
    type: ItemType.WEAPON,
    rarity: Rarity.RARE,
    description: 'A magical wand tipped with a glowing crystal.',
    weight: 3.0,
    magicAttack: 25,
    attack: 5,
    levelReq: 15,
    vocationReq: [Vocation.SORCERER, Vocation.DRUID],
    stackable: false,
    sellPrice: 250,
    buyPrice: 500,
    color: '#8e44ad',
    icon: '🪄',
  },
  golden_armor: {
    id: 'golden_armor',
    name: 'Golden Armor',
    type: ItemType.ARMOR,
    rarity: Rarity.EPIC,
    description: 'Armor made of pure gold. Surprisingly sturdy.',
    weight: 12.0,
    armor: 14,
    levelReq: 30,
    stackable: false,
    sellPrice: 1500,
    buyPrice: 3000,
    color: '#f1c40f',
    icon: '🎽',
  },
  boots_of_haste: {
    id: 'boots_of_haste',
    name: 'Boots of Haste',
    type: ItemType.BOOTS,
    rarity: Rarity.EPIC,
    description: 'Magical boots that make you incredibly fast.',
    weight: 1.0,
    armor: 2,
    speed: 2, // New stat effect conceptually
    levelReq: 25,
    stackable: false,
    sellPrice: 800,
    buyPrice: 1600,
    color: '#e67e22',
    icon: '👢',
  },
  magic_plate_armor: {
    id: 'magic_plate_armor',
    name: 'Magic Plate Armor',
    type: ItemType.ARMOR,
    rarity: Rarity.LEGENDARY,
    description: 'An ancient armor brimming with protective magic.',
    weight: 15.0,
    armor: 18,
    magicDefense: 5,
    levelReq: 40,
    stackable: false,
    sellPrice: 3500,
    buyPrice: 7000,
    color: '#3498db',
    icon: '👕',
  },

  // === CONSUMABLES ===
  health_potion_small: {
    id: 'health_potion_small',
    name: 'Small Health Potion',
    type: ItemType.CONSUMABLE,
    rarity: Rarity.COMMON,
    description: 'Restores 50 HP',
    weight: 0.5,
    healAmount: 50,
    levelReq: 1,
    stackable: true,
    sellPrice: 5,
    buyPrice: 10,
    color: '#ff4444',
    icon: '🧪',
  },
  health_potion_medium: {
    id: 'health_potion_medium',
    name: 'Medium Health Potion',
    type: ItemType.CONSUMABLE,
    rarity: Rarity.UNCOMMON,
    description: 'Restores 150 HP',
    weight: 0.7,
    healAmount: 150,
    levelReq: 5,
    stackable: true,
    sellPrice: 20,
    buyPrice: 40,
    color: '#ff2222',
    icon: '🧪',
  },
  health_potion_large: {
    id: 'health_potion_large',
    name: 'Large Health Potion',
    type: ItemType.CONSUMABLE,
    rarity: Rarity.RARE,
    description: 'Restores 400 HP',
    weight: 1.0,
    healAmount: 400,
    levelReq: 15,
    stackable: true,
    sellPrice: 80,
    buyPrice: 150,
    color: '#cc0000',
    icon: '🧪',
  },
  mana_potion_small: {
    id: 'mana_potion_small',
    name: 'Small Mana Potion',
    type: ItemType.CONSUMABLE,
    rarity: Rarity.COMMON,
    description: 'Restores 50 MP',
    weight: 0.5,
    manaAmount: 50,
    levelReq: 1,
    stackable: true,
    sellPrice: 5,
    buyPrice: 10,
    color: '#4444ff',
    icon: '🧪',
  },
  mana_potion_medium: {
    id: 'mana_potion_medium',
    name: 'Medium Mana Potion',
    type: ItemType.CONSUMABLE,
    rarity: Rarity.UNCOMMON,
    description: 'Restores 150 MP',
    weight: 0.7,
    manaAmount: 150,
    levelReq: 5,
    stackable: true,
    sellPrice: 20,
    buyPrice: 40,
    color: '#2222ff',
    icon: '🧪',
  },
  mana_potion_large: {
    id: 'mana_potion_large',
    name: 'Large Mana Potion',
    type: ItemType.CONSUMABLE,
    rarity: Rarity.RARE,
    description: 'Restores 400 MP',
    weight: 1.0,
    manaAmount: 400,
    levelReq: 15,
    stackable: true,
    sellPrice: 80,
    buyPrice: 150,
    color: '#0000cc',
    icon: '🧪',
  },

  // === WEAPONS ===
  wooden_sword: {
    id: 'wooden_sword',
    name: 'Wooden Sword',
    type: ItemType.WEAPON,
    rarity: Rarity.COMMON,
    description: 'A simple wooden sword.',
    weight: 3.0,
    attack: 5,
    levelReq: 1,
    stackable: false,
    sellPrice: 10,
    buyPrice: 20,
    color: '#a0784c',
    icon: '🗡️',
  },
  short_sword: {
    id: 'short_sword',
    name: 'Short Sword',
    type: ItemType.WEAPON,
    rarity: Rarity.COMMON,
    description: 'A basic iron sword.',
    weight: 4.0,
    attack: 10,
    levelReq: 3,
    stackable: false,
    sellPrice: 30,
    buyPrice: 60,
    color: '#b0b0b0',
    icon: '⚔️',
  },
  long_sword: {
    id: 'long_sword',
    name: 'Long Sword',
    type: ItemType.WEAPON,
    rarity: Rarity.UNCOMMON,
    description: 'A well-crafted long sword.',
    weight: 5.5,
    attack: 18,
    levelReq: 8,
    vocationReq: [Vocation.KNIGHT, Vocation.PALADIN],
    stackable: false,
    sellPrice: 100,
    buyPrice: 200,
    color: '#c0c0c0',
    icon: '⚔️',
  },
  battle_axe: {
    id: 'battle_axe',
    name: 'Battle Axe',
    type: ItemType.WEAPON,
    rarity: Rarity.UNCOMMON,
    description: 'A heavy but powerful axe.',
    weight: 7.0,
    attack: 25,
    levelReq: 12,
    vocationReq: [Vocation.KNIGHT],
    stackable: false,
    sellPrice: 200,
    buyPrice: 400,
    color: '#888888',
    icon: '🪓',
  },
  magic_staff: {
    id: 'magic_staff',
    name: 'Magic Staff',
    type: ItemType.WEAPON,
    rarity: Rarity.UNCOMMON,
    description: 'A staff imbued with magical energy.',
    weight: 3.0,
    magicAttack: 20,
    levelReq: 5,
    vocationReq: [Vocation.SORCERER, Vocation.DRUID],
    stackable: false,
    sellPrice: 120,
    buyPrice: 250,
    color: '#9b59b6',
    icon: '🪄',
  },
  dragon_sword: {
    id: 'dragon_sword',
    name: 'Dragon Sword',
    type: ItemType.WEAPON,
    rarity: Rarity.EPIC,
    description: 'A legendary sword forged in dragon fire.',
    weight: 6.0,
    attack: 40,
    magicAttack: 10,
    levelReq: 25,
    vocationReq: [Vocation.KNIGHT],
    stackable: false,
    sellPrice: 500,
    buyPrice: 1000,
    color: '#e74c3c',
    icon: '⚔️',
  },
  crossbow: {
    id: 'crossbow',
    name: 'Crossbow',
    type: ItemType.WEAPON,
    rarity: Rarity.UNCOMMON,
    description: 'A powerful ranged weapon.',
    weight: 5.0,
    attack: 15,
    levelReq: 8,
    vocationReq: [Vocation.PALADIN],
    stackable: false,
    sellPrice: 150,
    buyPrice: 300,
    color: '#8B4513',
    icon: '🏹',
  },
  arcane_staff: {
    id: 'arcane_staff',
    name: 'Arcane Staff',
    type: ItemType.WEAPON,
    rarity: Rarity.RARE,
    description: 'A staff pulsing with arcane energy.',
    weight: 3.5,
    magicAttack: 40,
    levelReq: 12,
    vocationReq: [Vocation.SORCERER, Vocation.DRUID],
    stackable: false,
    sellPrice: 350,
    buyPrice: 700,
    color: '#8e44ad',
    icon: '🪄',
  },
  inferno_staff: {
    id: 'inferno_staff',
    name: 'Inferno Staff',
    type: ItemType.WEAPON,
    rarity: Rarity.EPIC,
    description: 'A legendary staff wreathed in eternal flames.',
    weight: 4.0,
    magicAttack: 70,
    attack: 10,
    levelReq: 25,
    vocationReq: [Vocation.SORCERER],
    stackable: false,
    sellPrice: 800,
    buyPrice: 1600,
    color: '#e74c3c',
    icon: '🪄',
  },
  elven_bow: {
    id: 'elven_bow',
    name: 'Elven Bow',
    type: ItemType.WEAPON,
    rarity: Rarity.RARE,
    description: 'A beautifully crafted elven bow.',
    weight: 3.5,
    attack: 25,
    levelReq: 15,
    vocationReq: [Vocation.PALADIN],
    stackable: false,
    sellPrice: 300,
    buyPrice: 600,
    color: '#27ae60',
    icon: '🏹',
  },

  // === ARMOR ===
  leather_armor: {
    id: 'leather_armor',
    name: 'Leather Armor',
    type: ItemType.ARMOR,
    rarity: Rarity.COMMON,
    description: 'Basic leather protection.',
    weight: 5.0,
    defense: 5,
    levelReq: 1,
    stackable: false,
    sellPrice: 15,
    buyPrice: 30,
    color: '#8B4513',
    icon: '🦺',
  },
  chain_mail: {
    id: 'chain_mail',
    name: 'Chain Mail',
    type: ItemType.ARMOR,
    rarity: Rarity.UNCOMMON,
    description: 'Interlocking metal rings provide good protection.',
    weight: 10.0,
    defense: 15,
    levelReq: 8,
    stackable: false,
    sellPrice: 150,
    buyPrice: 300,
    color: '#a0a0a0',
    icon: '🛡️',
  },
  plate_armor: {
    id: 'plate_armor',
    name: 'Plate Armor',
    type: ItemType.ARMOR,
    rarity: Rarity.RARE,
    description: 'Heavy steel plates offer excellent protection.',
    weight: 18.0,
    defense: 30,
    levelReq: 18,
    vocationReq: [Vocation.KNIGHT, Vocation.PALADIN],
    stackable: false,
    sellPrice: 400,
    buyPrice: 800,
    color: '#d0d0d0',
    icon: '🛡️',
  },
  mage_robe: {
    id: 'mage_robe',
    name: 'Mage Robe',
    type: ItemType.ARMOR,
    rarity: Rarity.UNCOMMON,
    description: 'A robe enchanted with protective magic.',
    weight: 3.0,
    defense: 5,
    magicDefense: 15,
    levelReq: 5,
    vocationReq: [Vocation.SORCERER, Vocation.DRUID],
    stackable: false,
    sellPrice: 120,
    buyPrice: 250,
    color: '#6c3483',
    icon: '🧥',
  },
  mystic_robe: {
    id: 'mystic_robe',
    name: 'Mystic Robe',
    type: ItemType.ARMOR,
    rarity: Rarity.RARE,
    description: 'A powerful robe woven with mystical threads.',
    weight: 3.0,
    defense: 8,
    magicDefense: 30,
    magicAttack: 10,
    levelReq: 15,
    vocationReq: [Vocation.SORCERER, Vocation.DRUID],
    stackable: false,
    sellPrice: 400,
    buyPrice: 800,
    color: '#4a235a',
    icon: '🧥',
  },

  // === SHIELDS ===
  wooden_shield: {
    id: 'wooden_shield',
    name: 'Wooden Shield',
    type: ItemType.SHIELD,
    rarity: Rarity.COMMON,
    description: 'A simple wooden shield.',
    weight: 4.0,
    defense: 4,
    levelReq: 1,
    stackable: false,
    sellPrice: 10,
    buyPrice: 20,
    color: '#a0784c',
    icon: '🛡️',
  },
  iron_shield: {
    id: 'iron_shield',
    name: 'Iron Shield',
    type: ItemType.SHIELD,
    rarity: Rarity.UNCOMMON,
    description: 'A sturdy iron shield.',
    weight: 8.0,
    defense: 12,
    levelReq: 8,
    vocationReq: [Vocation.KNIGHT, Vocation.PALADIN],
    stackable: false,
    sellPrice: 100,
    buyPrice: 200,
    color: '#808080',
    icon: '🛡️',
  },
  tower_shield: {
    id: 'tower_shield',
    name: 'Tower Shield',
    type: ItemType.SHIELD,
    rarity: Rarity.RARE,
    description: 'A massive shield that provides great protection.',
    weight: 15.0,
    defense: 25,
    levelReq: 20,
    vocationReq: [Vocation.KNIGHT],
    stackable: false,
    sellPrice: 350,
    buyPrice: 700,
    color: '#b0b0b0',
    icon: '🛡️',
  },

  // === HELMETS ===
  leather_helmet: {
    id: 'leather_helmet',
    name: 'Leather Helmet',
    type: ItemType.HELMET,
    rarity: Rarity.COMMON,
    description: 'A simple leather cap.',
    weight: 2.0,
    defense: 2,
    levelReq: 1,
    stackable: false,
    sellPrice: 5,
    buyPrice: 10,
    color: '#a0784c',
    icon: '⛑️',
  },
  iron_helmet: {
    id: 'iron_helmet',
    name: 'Iron Helmet',
    type: ItemType.HELMET,
    rarity: Rarity.UNCOMMON,
    description: 'A solid iron helmet.',
    weight: 5.0,
    defense: 8,
    levelReq: 8,
    stackable: false,
    sellPrice: 60,
    buyPrice: 120,
    color: '#808080',
    icon: '⛑️',
  },
  crown_helmet: {
    id: 'crown_helmet',
    name: 'Crown Helmet',
    type: ItemType.HELMET,
    rarity: Rarity.RARE,
    description: 'A regal helmet fit for royalty.',
    weight: 4.0,
    defense: 12,
    magicDefense: 5,
    levelReq: 20,
    stackable: false,
    sellPrice: 300,
    buyPrice: 600,
    color: '#ffd700',
    icon: '🪙',
    icon: '👑',
  },

  // === LEGS ===
  leather_legs: {
    id: 'leather_legs',
    name: 'Leather Legs',
    type: ItemType.LEGS,
    rarity: Rarity.COMMON,
    description: 'Basic leather leggings.',
    weight: 3.0,
    defense: 3,
    levelReq: 1,
    stackable: false,
    sellPrice: 8,
    buyPrice: 15,
    color: '#8B4513',
    icon: '👖',
  },
  chain_legs: {
    id: 'chain_legs',
    name: 'Chain Legs',
    type: ItemType.LEGS,
    rarity: Rarity.UNCOMMON,
    description: 'Chain mail leggings.',
    weight: 6.0,
    defense: 8,
    levelReq: 8,
    stackable: false,
    sellPrice: 80,
    buyPrice: 160,
    color: '#a0a0a0',
    icon: '👖',
  },

  // === BOOTS ===
  leather_boots: {
    id: 'leather_boots',
    name: 'Leather Boots',
    type: ItemType.BOOTS,
    rarity: Rarity.COMMON,
    description: 'Simple leather boots.',
    weight: 2.0,
    defense: 1,
    levelReq: 1,
    stackable: false,
    sellPrice: 5,
    buyPrice: 10,
    color: '#8B4513',
    icon: '👢',
  },
  steel_boots: {
    id: 'steel_boots',
    name: 'Steel Boots',
    type: ItemType.BOOTS,
    rarity: Rarity.UNCOMMON,
    description: 'Sturdy steel boots.',
    weight: 5.0,
    defense: 4,
    levelReq: 10,
    stackable: false,
    sellPrice: 100,
    buyPrice: 200,
    color: '#c0c0c0',
    icon: '👢',
  },
  enchanted_boots: {
    id: 'enchanted_boots',
    name: 'Enchanted Boots',
    type: ItemType.BOOTS,
    rarity: Rarity.RARE,
    description: 'Boots imbued with speed magic.',
    weight: 2.0,
    defense: 3,
    magicDefense: 8,
    levelReq: 12,
    stackable: false,
    sellPrice: 250,
    buyPrice: 500,
    color: '#9b59b6',
    icon: '👢',
  },

  // === RINGS ===
  ring_of_life: {
    id: 'ring_of_life',
    name: 'Ring of Life',
    type: ItemType.RING,
    rarity: Rarity.RARE,
    description: 'Slowly regenerates health.',
    weight: 0.1,
    defense: 3,
    levelReq: 10,
    stackable: false,
    sellPrice: 200,
    buyPrice: 400,
    color: '#ff0000',
    icon: '💍',
  },
  ring_of_mana: {
    id: 'ring_of_mana',
    name: 'Ring of Mana',
    type: ItemType.RING,
    rarity: Rarity.RARE,
    description: 'Increases mana regeneration.',
    weight: 0.1,
    magicDefense: 5,
    levelReq: 10,
    vocationReq: [Vocation.SORCERER, Vocation.DRUID],
    stackable: false,
    sellPrice: 200,
    buyPrice: 400,
    color: '#0000ff',
    icon: '💍',
  },

  // === EPIC/LEGENDARY WEAPONS (buyable) ===
  assassin_dagger: {
    id: 'assassin_dagger',
    name: 'Assassin Dagger',
    type: ItemType.WEAPON,
    rarity: Rarity.RARE,
    description: 'A deadly fast dagger for quick strikes.',
    weight: 2,
    attack: 22,
    levelReq: 10,
    vocationReq: [Vocation.KNIGHT, Vocation.PALADIN],
    stackable: false,
    sellPrice: 250,
    buyPrice: 500,
    color: '#455a64',
    icon: '🗡️',
  },
  crystal_sword: {
    id: 'crystal_sword',
    name: 'Crystal Sword',
    type: ItemType.WEAPON,
    rarity: Rarity.EPIC,
    description: 'A sword made of pure crystal, exceptionally sharp.',
    weight: 5,
    attack: 35,
    magicAttack: 15,
    levelReq: 18,
    vocationReq: [Vocation.KNIGHT, Vocation.PALADIN],
    stackable: false,
    sellPrice: 600,
    buyPrice: 1200,
    color: '#00bcd4',
    icon: '⚔️',
  },
  divine_staff: {
    id: 'divine_staff',
    name: 'Divine Staff',
    type: ItemType.WEAPON,
    rarity: Rarity.EPIC,
    description: 'A staff blessed by the gods themselves.',
    weight: 3.5,
    magicAttack: 60,
    attack: 5,
    levelReq: 18,
    vocationReq: [Vocation.SORCERER, Vocation.DRUID],
    stackable: false,
    sellPrice: 600,
    buyPrice: 1200,
    color: '#e91e63',
    icon: '🪄',
  },
  holy_crossbow: {
    id: 'holy_crossbow',
    name: 'Holy Crossbow',
    type: ItemType.WEAPON,
    rarity: Rarity.RARE,
    description: 'A crossbow imbued with holy power.',
    weight: 5,
    attack: 20,
    magicAttack: 10,
    levelReq: 12,
    vocationReq: [Vocation.PALADIN],
    stackable: false,
    sellPrice: 280,
    buyPrice: 550,
    color: '#ffd700',
    icon: '🪙',
    icon: '🏹',
  },

  // === EPIC ARMOR (buyable) ===
  knight_armor: {
    id: 'knight_armor',
    name: 'Knight Armor',
    type: ItemType.ARMOR,
    rarity: Rarity.EPIC,
    description: 'Armor worn by elite knights of the realm.',
    weight: 20,
    defense: 35,
    magicDefense: 5,
    levelReq: 22,
    vocationReq: [Vocation.KNIGHT],
    stackable: false,
    sellPrice: 500,
    buyPrice: 1000,
    color: '#b71c1c',
    icon: '🛡️',
  },
  druid_cloak: {
    id: 'druid_cloak',
    name: 'Druid Cloak',
    type: ItemType.ARMOR,
    rarity: Rarity.RARE,
    description: 'A cloak woven from enchanted forest fibers.',
    weight: 2,
    defense: 6,
    magicDefense: 20,
    magicAttack: 8,
    levelReq: 12,
    vocationReq: [Vocation.DRUID, Vocation.SORCERER],
    stackable: false,
    sellPrice: 300,
    buyPrice: 600,
    color: '#2e7d32',
    icon: '🧥',
  },

  // === RARE LEGS (buyable) ===
  plate_legs: {
    id: 'plate_legs',
    name: 'Plate Legs',
    type: ItemType.LEGS,
    rarity: Rarity.RARE,
    description: 'Heavy plate leggings for maximum leg protection.',
    weight: 8,
    defense: 12,
    levelReq: 14,
    stackable: false,
    sellPrice: 150,
    buyPrice: 300,
    color: '#90a4ae',
    icon: '👖',
  },

  // === NEW ACCESSORIES (buyable) ===
  amulet_of_power: {
    id: 'amulet_of_power',
    name: 'Amulet of Power',
    type: ItemType.AMULET,
    rarity: Rarity.RARE,
    description: 'An amulet that boosts all offensive stats.',
    weight: 0.1,
    attack: 5,
    magicAttack: 5,
    levelReq: 10,
    stackable: false,
    sellPrice: 300,
    buyPrice: 600,
    color: '#ff6f00',
    icon: '📿',
  },
  ring_of_fire: {
    id: 'ring_of_fire',
    name: 'Ring of Fire',
    type: ItemType.RING,
    rarity: Rarity.EPIC,
    description: 'A ring that burns with eternal flame, boosting fire magic.',
    weight: 0.1,
    magicAttack: 15,
    magicDefense: 5,
    levelReq: 15,
    vocationReq: [Vocation.SORCERER],
    stackable: false,
    sellPrice: 400,
    buyPrice: 800,
    color: '#ff5722',
    icon: '💍',
  },
  ring_of_ice: {
    id: 'ring_of_ice',
    name: 'Ring of Ice',
    type: ItemType.RING,
    rarity: Rarity.EPIC,
    description: 'A ring that radiates cold energy.',
    weight: 0.1,
    magicDefense: 15,
    magicAttack: 8,
    levelReq: 15,
    vocationReq: [Vocation.DRUID, Vocation.SORCERER],
    stackable: false,
    sellPrice: 400,
    buyPrice: 800,
    color: '#03a9f4',
    icon: '💍',
  },

  // === ULTRA POTIONS (buyable) ===
  health_potion_ultra: {
    id: 'health_potion_ultra',
    name: 'Ultra Health Potion',
    type: ItemType.CONSUMABLE,
    rarity: Rarity.EPIC,
    description: 'Restores 1000 HP.',
    weight: 1.5,
    healAmount: 1000,
    levelReq: 25,
    stackable: true,
    sellPrice: 200,
    buyPrice: 400,
    color: '#880000',
    icon: '🧪',
  },
  mana_potion_ultra: {
    id: 'mana_potion_ultra',
    name: 'Ultra Mana Potion',
    type: ItemType.CONSUMABLE,
    rarity: Rarity.EPIC,
    description: 'Restores 1000 MP.',
    weight: 1.5,
    manaAmount: 1000,
    levelReq: 25,
    stackable: true,
    sellPrice: 200,
    buyPrice: 400,
    color: '#000088',
    icon: '🧪',
  },

  // === NEW WEAPONS ===
  shadow_blade: {
    id: 'shadow_blade',
    name: 'Shadow Blade',
    type: ItemType.WEAPON,
    rarity: Rarity.EPIC,
    description: 'A blade forged in pure darkness.',
    weight: 4.5,
    attack: 30,
    magicAttack: 20,
    levelReq: 20,
    vocationReq: [Vocation.KNIGHT, Vocation.PALADIN],
    stackable: false,
    sellPrice: 550,
    buyPrice: 1100,
    color: '#37474f',
    icon: '⚔️',
  },
  sage_wand: {
    id: 'sage_wand',
    name: 'Sage Wand',
    type: ItemType.WEAPON,
    rarity: Rarity.RARE,
    description: 'A wand favored by wise sorcerers.',
    weight: 2,
    magicAttack: 45,
    levelReq: 10,
    vocationReq: [Vocation.SORCERER, Vocation.DRUID],
    stackable: false,
    sellPrice: 200,
    buyPrice: 400,
    color: '#7b1fa2',
    icon: '🪄',
  },
  paladin_lance: {
    id: 'paladin_lance',
    name: 'Paladin Lance',
    type: ItemType.WEAPON,
    rarity: Rarity.RARE,
    description: 'A lance designed for holy warriors.',
    weight: 6,
    attack: 22,
    magicAttack: 8,
    levelReq: 12,
    vocationReq: [Vocation.PALADIN],
    stackable: false,
    sellPrice: 220,
    buyPrice: 440,
    color: '#fbc02d',
    icon: '🏹',
  },

  // === NEW ARMOR ===
  dragon_helmet: {
    id: 'dragon_helmet',
    name: 'Dragon Helm',
    type: ItemType.HELMET,
    rarity: Rarity.EPIC,
    description: 'A helmet crafted from dragon scales.',
    weight: 5,
    defense: 15,
    magicDefense: 8,
    levelReq: 22,
    stackable: false,
    sellPrice: 350,
    buyPrice: 700,
    color: '#b71c1c',
    icon: '⛑️',
  },
  mage_hood: {
    id: 'mage_hood',
    name: 'Mage Hood',
    type: ItemType.HELMET,
    rarity: Rarity.UNCOMMON,
    description: 'A comfortable hood for mages.',
    weight: 1,
    defense: 3,
    magicDefense: 10,
    levelReq: 5,
    vocationReq: [Vocation.SORCERER, Vocation.DRUID],
    stackable: false,
    sellPrice: 80,
    buyPrice: 160,
    color: '#4a148c',
    icon: '🎩',
  },
  enchanted_shield: {
    id: 'enchanted_shield',
    name: 'Enchanted Shield',
    type: ItemType.SHIELD,
    rarity: Rarity.EPIC,
    description: 'A shield glowing with protective magic.',
    weight: 8,
    defense: 18,
    magicDefense: 12,
    levelReq: 18,
    vocationReq: [Vocation.KNIGHT, Vocation.PALADIN],
    stackable: false,
    sellPrice: 350,
    buyPrice: 700,
    color: '#00897b',
    icon: '🛡️',
  },
  paladin_boots: {
    id: 'paladin_boots',
    name: 'Paladin Boots',
    type: ItemType.BOOTS,
    rarity: Rarity.UNCOMMON,
    description: 'Light boots for swift paladins.',
    weight: 2.5,
    defense: 3,
    levelReq: 6,
    vocationReq: [Vocation.PALADIN],
    stackable: false,
    sellPrice: 80,
    buyPrice: 160,
    color: '#f9a825',
    icon: '👢',
  },

  // === NEW ACCESSORIES ===
  amulet_of_wisdom: {
    id: 'amulet_of_wisdom',
    name: 'Amulet of Wisdom',
    type: ItemType.AMULET,
    rarity: Rarity.EPIC,
    description: 'Greatly boosts magical power.',
    weight: 0.1,
    magicAttack: 12,
    magicDefense: 8,
    levelReq: 15,
    vocationReq: [Vocation.SORCERER, Vocation.DRUID],
    stackable: false,
    sellPrice: 400,
    buyPrice: 800,
    color: '#6a1b9a',
    icon: '📿',
  },
  warrior_amulet: {
    id: 'warrior_amulet',
    name: 'Warrior Amulet',
    type: ItemType.AMULET,
    rarity: Rarity.RARE,
    description: 'Boosts physical combat prowess.',
    weight: 0.1,
    attack: 8,
    defense: 5,
    levelReq: 12,
    vocationReq: [Vocation.KNIGHT, Vocation.PALADIN],
    stackable: false,
    sellPrice: 250,
    buyPrice: 500,
    color: '#e65100',
    icon: '📿',
  },
  ring_of_fortune: {
    id: 'ring_of_fortune',
    name: 'Ring of Fortune',
    type: ItemType.RING,
    rarity: Rarity.EPIC,
    description: 'A ring that brings luck in battle.',
    weight: 0.1,
    attack: 5,
    defense: 5,
    magicAttack: 5,
    magicDefense: 5,
    levelReq: 20,
    stackable: false,
    sellPrice: 500,
    buyPrice: 1000,
    color: '#ffd600',
    icon: '💍',
  },

  // === GRAND POTIONS ===
  health_potion_grand: {
    id: 'health_potion_grand',
    name: 'Grand Health Potion',
    type: ItemType.CONSUMABLE,
    rarity: Rarity.UNCOMMON,
    description: 'Restores 250 HP.',
    weight: 0.8,
    healAmount: 250,
    levelReq: 10,
    stackable: true,
    sellPrice: 40,
    buyPrice: 80,
    color: '#cc3333',
    icon: '🧪',
  },
  mana_potion_grand: {
    id: 'mana_potion_grand',
    name: 'Grand Mana Potion',
    type: ItemType.CONSUMABLE,
    rarity: Rarity.UNCOMMON,
    description: 'Restores 250 MP.',
    weight: 0.8,
    manaAmount: 250,
    levelReq: 10,
    stackable: true,
    sellPrice: 40,
    buyPrice: 80,
    color: '#3333cc',
    icon: '🧪',
  },

  // === LEGENDARY WEAPONS ===
  excalibur: {
    id: 'excalibur',
    name: 'Excalibur',
    type: ItemType.WEAPON,
    rarity: Rarity.LEGENDARY,
    description: 'The legendary sword of kings. Unmatched power.',
    weight: 7,
    attack: 55,
    magicAttack: 25,
    defense: 5,
    levelReq: 30,
    vocationReq: [Vocation.KNIGHT],
    stackable: false,
    sellPrice: 2000,
    buyPrice: 4000,
    color: '#ffd700',
    icon: '🪙',
    icon: '⚔️',
  },
  staff_of_destruction: {
    id: 'staff_of_destruction',
    name: 'Staff of Destruction',
    type: ItemType.WEAPON,
    rarity: Rarity.LEGENDARY,
    description: 'A staff that channels the raw power of destruction.',
    weight: 4,
    magicAttack: 100,
    attack: 15,
    levelReq: 30,
    vocationReq: [Vocation.SORCERER],
    stackable: false,
    sellPrice: 2000,
    buyPrice: 4000,
    color: '#d50000',
    icon: '🪄',
  },
  nature_staff: {
    id: 'nature_staff',
    name: 'Staff of the Wild',
    type: ItemType.WEAPON,
    rarity: Rarity.EPIC,
    description: 'A living staff that pulses with nature energy.',
    weight: 3,
    magicAttack: 75,
    defense: 5,
    magicDefense: 10,
    levelReq: 22,
    vocationReq: [Vocation.DRUID],
    stackable: false,
    sellPrice: 900,
    buyPrice: 1800,
    color: '#388e3c',
    icon: '🪄',
  },
  sniper_crossbow: {
    id: 'sniper_crossbow',
    name: 'Sniper Crossbow',
    type: ItemType.WEAPON,
    rarity: Rarity.EPIC,
    description: 'A precision crossbow with extreme range and damage.',
    weight: 5.5,
    attack: 35,
    magicAttack: 15,
    levelReq: 20,
    vocationReq: [Vocation.PALADIN],
    stackable: false,
    sellPrice: 700,
    buyPrice: 1400,
    color: '#546e7a',
    icon: '🏹',
  },

  // === LEGENDARY ARMOR ===
  dragon_scale_armor: {
    id: 'dragon_scale_armor',
    name: 'Dragon Scale Armor',
    type: ItemType.ARMOR,
    rarity: Rarity.LEGENDARY,
    description: 'Armor forged from dragon scales. Nearly impenetrable.',
    weight: 22,
    defense: 50,
    magicDefense: 15,
    levelReq: 30,
    vocationReq: [Vocation.KNIGHT],
    stackable: false,
    sellPrice: 2000,
    buyPrice: 4000,
    color: '#b71c1c',
    icon: '🛡️',
  },
  archmage_robe: {
    id: 'archmage_robe',
    name: 'Archmage Robe',
    type: ItemType.ARMOR,
    rarity: Rarity.LEGENDARY,
    description: 'A robe woven from pure magical energy.',
    weight: 2.5,
    defense: 10,
    magicDefense: 45,
    magicAttack: 20,
    levelReq: 28,
    vocationReq: [Vocation.SORCERER],
    stackable: false,
    sellPrice: 1800,
    buyPrice: 3600,
    color: '#4a148c',
    icon: '🧥',
  },
  ancient_bark_armor: {
    id: 'ancient_bark_armor',
    name: 'Ancient Bark Armor',
    type: ItemType.ARMOR,
    rarity: Rarity.EPIC,
    description: 'Living armor made from ancient tree bark.',
    weight: 8,
    defense: 20,
    magicDefense: 25,
    magicAttack: 12,
    levelReq: 20,
    vocationReq: [Vocation.DRUID],
    stackable: false,
    sellPrice: 800,
    buyPrice: 1600,
    color: '#33691e',
    icon: '🧥',
  },
  templar_armor: {
    id: 'templar_armor',
    name: 'Templar Armor',
    type: ItemType.ARMOR,
    rarity: Rarity.EPIC,
    description: 'Sacred armor of the Templar order.',
    weight: 16,
    defense: 32,
    magicDefense: 10,
    levelReq: 22,
    vocationReq: [Vocation.PALADIN],
    stackable: false,
    sellPrice: 900,
    buyPrice: 1800,
    color: '#f9a825',
    icon: '🛡️',
  },

  // === LEGENDARY HELMETS ===
  kings_crown: {
    id: 'kings_crown',
    name: "King's Crown",
    type: ItemType.HELMET,
    rarity: Rarity.LEGENDARY,
    description: 'A crown that grants wisdom and protection.',
    weight: 3,
    defense: 15,
    magicDefense: 15,
    magicAttack: 10,
    levelReq: 28,
    stackable: false,
    sellPrice: 1500,
    buyPrice: 3000,
    color: '#ffd600',
    icon: '👑',
  },
  visor_of_shadow: {
    id: 'visor_of_shadow',
    name: 'Visor of Shadow',
    type: ItemType.HELMET,
    rarity: Rarity.EPIC,
    description: 'A dark visor that enhances perception in combat.',
    weight: 3,
    defense: 10,
    attack: 8,
    levelReq: 20,
    stackable: false,
    sellPrice: 500,
    buyPrice: 1000,
    color: '#263238',
    icon: '⛑️',
  },

  // === LEGENDARY SHIELDS ===
  aegis: {
    id: 'aegis',
    name: 'Aegis',
    type: ItemType.SHIELD,
    rarity: Rarity.LEGENDARY,
    description: 'The legendary shield of the gods. Impenetrable.',
    weight: 12,
    defense: 35,
    magicDefense: 20,
    levelReq: 30,
    vocationReq: [Vocation.KNIGHT],
    stackable: false,
    sellPrice: 2000,
    buyPrice: 4000,
    color: '#ffd700',
    icon: '🪙',
    icon: '🛡️',
  },
  buckler_of_dawn: {
    id: 'buckler_of_dawn',
    name: 'Buckler of Dawn',
    type: ItemType.SHIELD,
    rarity: Rarity.RARE,
    description: 'A small shield that glows at sunrise.',
    weight: 5,
    defense: 15,
    magicDefense: 8,
    levelReq: 14,
    vocationReq: [Vocation.KNIGHT, Vocation.PALADIN],
    stackable: false,
    sellPrice: 300,
    buyPrice: 600,
    color: '#ffb74d',
    icon: '🛡️',
  },

  // === LEGENDARY BOOTS ===
  boots_of_speed: {
    id: 'boots_of_speed',
    name: 'Boots of Speed',
    type: ItemType.BOOTS,
    rarity: Rarity.EPIC,
    description: 'Enchanted boots that make you incredibly fast.',
    weight: 1,
    defense: 4,
    magicDefense: 6,
    levelReq: 18,
    stackable: false,
    sellPrice: 400,
    buyPrice: 800,
    color: '#00e676',
    icon: '👢',
  },
  iron_greaves: {
    id: 'iron_greaves',
    name: 'Iron Greaves',
    type: ItemType.BOOTS,
    rarity: Rarity.RARE,
    description: 'Heavy boots with reinforced plating.',
    weight: 6,
    defense: 8,
    levelReq: 15,
    vocationReq: [Vocation.KNIGHT],
    stackable: false,
    sellPrice: 200,
    buyPrice: 400,
    color: '#78909c',
    icon: '👢',
  },

  // === LEGENDARY LEGS ===
  dragon_leggings: {
    id: 'dragon_leggings',
    name: 'Dragon Leggings',
    type: ItemType.LEGS,
    rarity: Rarity.EPIC,
    description: 'Leggings made from dragon leather.',
    weight: 6,
    defense: 15,
    magicDefense: 8,
    levelReq: 22,
    stackable: false,
    sellPrice: 400,
    buyPrice: 800,
    color: '#c62828',
    icon: '👖',
  },

  // === LEGENDARY ACCESSORIES ===
  pendant_of_vitality: {
    id: 'pendant_of_vitality',
    name: 'Pendant of Vitality',
    type: ItemType.AMULET,
    rarity: Rarity.EPIC,
    description: 'A pendant that greatly increases maximum health.',
    weight: 0.1,
    defense: 10,
    magicDefense: 10,
    levelReq: 20,
    stackable: false,
    sellPrice: 500,
    buyPrice: 1000,
    color: '#c62828',
    icon: '📿',
  },
  ring_of_the_abyss: {
    id: 'ring_of_the_abyss',
    name: 'Ring of the Abyss',
    type: ItemType.RING,
    rarity: Rarity.LEGENDARY,
    description: 'A ring that draws power from the abyss itself.',
    weight: 0.1,
    magicAttack: 25,
    magicDefense: 10,
    levelReq: 25,
    vocationReq: [Vocation.SORCERER, Vocation.DRUID],
    stackable: false,
    sellPrice: 1200,
    buyPrice: 2400,
    color: '#311b92',
    icon: '💍',
  },
  berserker_ring: {
    id: 'berserker_ring',
    name: 'Berserker Ring',
    type: ItemType.RING,
    rarity: Rarity.EPIC,
    description: 'A ring that fills the wearer with rage.',
    weight: 0.1,
    attack: 12,
    defense: 3,
    levelReq: 18,
    vocationReq: [Vocation.KNIGHT, Vocation.PALADIN],
    stackable: false,
    sellPrice: 500,
    buyPrice: 1000,
    color: '#d32f2f',
    icon: '💍',
  },

  // === GOLD ===
  gold_coin: {
    id: 'gold_coin',
    name: 'Gold Coin',
    type: ItemType.GOLD,
    rarity: Rarity.COMMON,
    description: 'Shiny gold coin.',
    weight: 0.01,
    levelReq: 1,
    stackable: true,
    sellPrice: 1,
    buyPrice: 0,
    color: '#ffd700',
    icon: '🪙',
    icon: '🪙',
  },

  // === NEW CRAFTING MATERIALS ===
  raw_meat: {
    id: 'raw_meat', name: 'Raw Meat', type: ItemType.CONSUMABLE, rarity: Rarity.COMMON,
    description: 'Raw meat from a hunted animal. Can be eaten for a small heal.',
    weight: 1.5, healAmount: 25, levelReq: 1, stackable: true, sellPrice: 2, buyPrice: 5,
    color: '#8B0000', icon: '🥩',
  },
  bear_pelt: {
    id: 'bear_pelt', name: 'Bear Pelt', type: ItemType.CONSUMABLE, rarity: Rarity.UNCOMMON,
    description: 'A thick bear pelt. Sells for a good price.',
    weight: 3, levelReq: 1, stackable: true, sellPrice: 50, buyPrice: 0,
    color: '#5C3317', icon: '🧶',
  },
  crocodile_skin: {
    id: 'crocodile_skin', name: 'Crocodile Skin', type: ItemType.CONSUMABLE, rarity: Rarity.UNCOMMON,
    description: 'Tough crocodile hide. Valuable to merchants.',
    weight: 2.5, levelReq: 1, stackable: true, sellPrice: 40, buyPrice: 0,
    color: '#2E5A1E', icon: '🪶',
  },
  feather: {
    id: 'feather', name: 'Feather', type: ItemType.CONSUMABLE, rarity: Rarity.COMMON,
    description: 'A large bird feather. Used in crafting.',
    weight: 0.1, levelReq: 1, stackable: true, sellPrice: 3, buyPrice: 0,
    color: '#D2B48C', icon: '🪶',
  },
  crab_claw: {
    id: 'crab_claw', name: 'Crab Claw', type: ItemType.CONSUMABLE, rarity: Rarity.COMMON,
    description: 'A sharp crab claw. Can be used as a weapon or sold.',
    weight: 0.8, attack: 5, levelReq: 1, stackable: true, sellPrice: 8, buyPrice: 0,
    color: '#B22222', icon: '🦀',
  },
  minotaur_horn: {
    id: 'minotaur_horn', name: 'Minotaur Horn', type: ItemType.CONSUMABLE, rarity: Rarity.RARE,
    description: 'A fearsome minotaur horn. Highly valued.',
    weight: 2, levelReq: 1, stackable: true, sellPrice: 80, buyPrice: 0,
    color: '#DAA520', icon: '📯',
  },
  snake_venom: {
    id: 'snake_venom', name: 'Snake Venom', type: ItemType.CONSUMABLE, rarity: Rarity.UNCOMMON,
    description: 'Potent venom extracted from a cobra.',
    weight: 0.3, levelReq: 1, stackable: true, sellPrice: 25, buyPrice: 0,
    color: '#00ff00', icon: '毒素',
  },

  // === NEW EQUIPMENT ===
  bone_sword: {
    id: 'bone_sword', name: 'Bone Sword', type: ItemType.WEAPON, rarity: Rarity.COMMON,
    description: 'A crude sword made from giant bones.', weight: 3, attack: 8, levelReq: 1,
    stackable: false, sellPrice: 15, buyPrice: 35, color: '#E8DCC8', icon: '🗡️',
  },
  spiked_club: {
    id: 'spiked_club', name: 'Spiked Club', type: ItemType.WEAPON, rarity: Rarity.UNCOMMON,
    description: 'A heavy club with iron spikes.', weight: 5, attack: 14, levelReq: 3,
    stackable: false, sellPrice: 30, buyPrice: 70, color: '#5A3A1A', icon: '🏏',
  },
  hunter_bow: {
    id: 'hunter_bow', name: 'Hunter Bow', type: ItemType.WEAPON, rarity: Rarity.UNCOMMON,
    description: 'A well-crafted bow for hunting.', weight: 2.5, attack: 12, levelReq: 5,
    vocationReq: [Vocation.PALADIN], stackable: false, sellPrice: 45, buyPrice: 100, color: '#8B4513', icon: '🏹',
  },
  rune_blade: {
    id: 'rune_blade', name: 'Rune Blade', type: ItemType.WEAPON, rarity: Rarity.EPIC,
    description: 'A blade etched with ancient runes.', weight: 4, attack: 38, magicAttack: 10, levelReq: 15,
    stackable: false, sellPrice: 800, buyPrice: 0, color: '#4169E1', icon: '⚔️',
  },
  tribal_shield: {
    id: 'tribal_shield', name: 'Tribal Shield', type: ItemType.SHIELD, rarity: Rarity.COMMON,
    description: 'A wooden shield with tribal markings.', weight: 4, defense: 6, levelReq: 1,
    stackable: false, sellPrice: 20, buyPrice: 45, color: '#6B4226', icon: '🛡️',
  },
  iron_helm: {
    id: 'iron_helm', name: 'Iron Helm', type: ItemType.HELMET, rarity: Rarity.UNCOMMON,
    description: 'A sturdy iron helmet.', weight: 3, defense: 5, levelReq: 5,
    stackable: false, sellPrice: 40, buyPrice: 90, color: '#6A6A6A', icon: '⛑️',
  },
  wolf_pelt_cloak: {
    id: 'wolf_pelt_cloak', name: 'Wolf Pelt Cloak', type: ItemType.ARMOR, rarity: Rarity.UNCOMMON,
    description: 'A warm cloak made from wolf pelts.', weight: 2, defense: 4, levelReq: 3,
    stackable: false, sellPrice: 35, buyPrice: 80, color: '#6B6B6B', icon: '🧥',
  },

  // === TASK 5-6: NEW CRAFTING MATERIALS ===
  golem_core: {
    id: 'golem_core', name: 'Golem Core', type: ItemType.CONSUMABLE, rarity: Rarity.RARE,
    description: 'A glowing crystal core from a stone golem.', weight: 2, levelReq: 1,
    stackable: true, sellPrice: 150, buyPrice: 0, color: '#00CED1', icon: '💎',
  },
  ghost_essence: {
    id: 'ghost_essence', name: 'Ghost Essence', type: ItemType.CONSUMABLE, rarity: Rarity.UNCOMMON,
    description: 'Ectoplasm from a defeated ghost.', weight: 0.5, levelReq: 1,
    stackable: true, sellPrice: 40, buyPrice: 0, color: '#B0C4DE', icon: '🫧',
  },
  eagle_talon: {
    id: 'eagle_talon', name: 'Eagle Talon', type: ItemType.CONSUMABLE, rarity: Rarity.UNCOMMON,
    description: 'Sharp talon from a mountain eagle.', weight: 0.3, levelReq: 1,
    stackable: true, sellPrice: 25, buyPrice: 0, color: '#DAA520', icon: '🦴',
  },
  tortoise_shell: {
    id: 'tortoise_shell', name: 'Tortoise Shell', type: ItemType.CONSUMABLE, rarity: Rarity.UNCOMMON,
    description: 'Sturdy shell from a thornback.', weight: 3, levelReq: 1,
    stackable: true, sellPrice: 35, buyPrice: 0, color: '#556B2F', icon: '🛡️',
  },
  war_wolf_fang: {
    id: 'war_wolf_fang', name: 'War Wolf Fang', type: ItemType.CONSUMABLE, rarity: Rarity.RARE,
    description: 'Sharp fang from a war wolf.', weight: 0.2, levelReq: 1,
    stackable: true, sellPrice: 60, buyPrice: 0, color: '#FFFFFF', icon: '🦷',
  },

  // === TASK 5-6: NEW EQUIPMENT ===
  war_hammer: {
    id: 'war_hammer', name: 'War Hammer', type: ItemType.WEAPON, rarity: Rarity.RARE,
    description: 'Crushes enemies with tremendous force.', weight: 8, attack: 38, levelReq: 20,
    vocationReq: [Vocation.KNIGHT], stackable: false, sellPrice: 800, buyPrice: 2000,
    color: '#708090', icon: '🔨',
  },
  frost_staff: {
    id: 'frost_staff', name: 'Frost Staff', type: ItemType.WEAPON, rarity: Rarity.EPIC,
    description: 'Channels ice magic.', weight: 4, magicAttack: 55, levelReq: 25,
    vocationReq: [Vocation.SORCERER, Vocation.DRUID], stackable: false, sellPrice: 1500, buyPrice: 4000,
    color: '#00BFFF', icon: '🪄',
  },
  hunting_crossbow: {
    id: 'hunting_crossbow', name: 'Hunting Crossbow', type: ItemType.WEAPON, rarity: Rarity.UNCOMMON,
    description: 'Fast and deadly.', weight: 5, attack: 22, levelReq: 12,
    vocationReq: [Vocation.PALADIN], stackable: false, sellPrice: 300, buyPrice: 800,
    color: '#8B4513', icon: '🏹',
  },
  shadow_cloak: {
    id: 'shadow_cloak', name: 'Shadow Cloak', type: ItemType.ARMOR, rarity: Rarity.EPIC,
    description: 'Makes you nearly invisible.', weight: 3, defense: 28, magicDefense: 20, levelReq: 30,
    stackable: false, sellPrice: 2000, buyPrice: 5000, color: '#1a1a2e', icon: '🧥',
  },
  iron_gauntlets: {
    id: 'iron_gauntlets', name: 'Iron Gauntlets', type: ItemType.ARMOR, rarity: Rarity.UNCOMMON,
    description: 'Heavy but protective.', weight: 4, defense: 12, levelReq: 10,
    vocationReq: [Vocation.KNIGHT, Vocation.PALADIN], stackable: false, sellPrice: 200, buyPrice: 500,
    color: '#696969', icon: '🧤',
  },
  tortoise_shield: {
    id: 'tortoise_shield', name: 'Tortoise Shield', type: ItemType.SHIELD, rarity: Rarity.RARE,
    description: 'Incredible defense.', weight: 6, defense: 22, levelReq: 18,
    stackable: false, sellPrice: 600, buyPrice: 1500, color: '#556B2F', icon: '🛡️',
  },
  wolf_helm: {
    id: 'wolf_helm', name: 'Wolf Helm', type: ItemType.HELMET, rarity: Rarity.UNCOMMON,
    description: 'Helm carved from a wolf\'s skull.', weight: 3, defense: 8, levelReq: 8,
    stackable: false, sellPrice: 150, buyPrice: 400, color: '#696969', icon: '⛑️',
  },
  gemstone_ring: {
    id: 'gemstone_ring', name: 'Gemstone Ring', type: ItemType.RING, rarity: Rarity.RARE,
    description: 'Boosts magic attack.', weight: 0.1, magicAttack: 15, levelReq: 22,
    stackable: false, sellPrice: 500, buyPrice: 1200, color: '#FF1493', icon: '💍',
  },
  mercenary_sword: {
    id: 'mercenary_sword', name: 'Mercenary Sword', type: ItemType.WEAPON, rarity: Rarity.UNCOMMON,
    description: 'Reliable blade.', weight: 5, attack: 20, levelReq: 10,
    stackable: false, sellPrice: 250, buyPrice: 600, color: '#C0C0C0', icon: '⚔️',
  },
  spirit_amulet: {
    id: 'spirit_amulet', name: 'Spirit Amulet', type: ItemType.AMULET, rarity: Rarity.RARE,
    description: 'Protects against undead.', weight: 0.5, magicDefense: 18, levelReq: 20,
    stackable: false, sellPrice: 400, buyPrice: 1000, color: '#9370DB', icon: '📿',
  },
};

export function getItem(id: string): ItemDefinition | undefined {
  return ITEMS[id];
}

export function getShopItems(shopItemIds: string[]): ItemDefinition[] {
  return shopItemIds.map(id => ITEMS[id]).filter(Boolean) as ItemDefinition[];
}