// =============================================
// Tibia-Style Game - Monster Definitions
// =============================================

import { MonsterDefinition } from './types';

export const MONSTERS: Record<string, MonsterDefinition> = {
  rat: {
    id: 'rat',
    name: 'Rat',
    health: 15,
    maxHealth: 15,
    attack: 3,
    defense: 1,
    speed: 2,
    experience: 10,
    lootTable: [
      { itemId: 'gold_coin', chance: 0.8, minQuantity: 1, maxQuantity: 5 },
      { itemId: 'health_potion_small', chance: 0.1, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#8B7355',
    icon: '🐀',
    aggressive: false,
    chaseRange: 3,
    attackRange: 1,
    attackSpeed: 2000,
  },
  snake: {
    id: 'snake',
    name: 'Snake',
    health: 25,
    maxHealth: 25,
    attack: 8,
    defense: 2,
    speed: 3,
    experience: 20,
    lootTable: [
      { itemId: 'gold_coin', chance: 0.9, minQuantity: 2, maxQuantity: 10 },
      { itemId: 'health_potion_small', chance: 0.15, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'mana_potion_small', chance: 0.1, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#2ecc71',
    icon: '🐍',
    aggressive: true,
    chaseRange: 5,
    attackRange: 1,
    attackSpeed: 1500,
  },
  spider: {
    id: 'spider',
    name: 'Giant Spider',
    health: 40,
    maxHealth: 40,
    attack: 12,
    defense: 5,
    speed: 3.5,
    experience: 35,
    lootTable: [
      { itemId: 'gold_coin', chance: 1, minQuantity: 5, maxQuantity: 20 },
      { itemId: 'health_potion_small', chance: 0.2, minQuantity: 1, maxQuantity: 2 },
      { itemId: 'leather_armor', chance: 0.05, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#2c3e50',
    icon: '🕷️',
    aggressive: true,
    chaseRange: 6,
    attackRange: 1,
    attackSpeed: 1200,
  },
  wolf: {
    id: 'wolf',
    name: 'Wolf',
    health: 60,
    maxHealth: 60,
    attack: 18,
    defense: 8,
    speed: 4.5,
    experience: 50,
    lootTable: [
      { itemId: 'gold_coin', chance: 1, minQuantity: 8, maxQuantity: 30 },
      { itemId: 'health_potion_medium', chance: 0.15, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'leather_helmet', chance: 0.08, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'leather_legs', chance: 0.08, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#7f8c8d',
    icon: '🐺',
    aggressive: true,
    chaseRange: 7,
    attackRange: 1,
    attackSpeed: 1500,
  },
  orc: {
    id: 'orc',
    name: 'Orc',
    health: 120,
    maxHealth: 120,
    attack: 25,
    defense: 15,
    speed: 3,
    experience: 80,
    lootTable: [
      { itemId: 'gold_coin', chance: 1, minQuantity: 15, maxQuantity: 50 },
      { itemId: 'health_potion_medium', chance: 0.25, minQuantity: 1, maxQuantity: 2 },
      { itemId: 'short_sword', chance: 0.1, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'chain_mail', chance: 0.05, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'iron_shield', chance: 0.05, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#27ae60',
    icon: '👹',
    aggressive: true,
    chaseRange: 8,
    attackRange: 1,
    attackSpeed: 1800,
  },
  skeleton: {
    id: 'skeleton',
    name: 'Skeleton',
    health: 80,
    maxHealth: 80,
    attack: 20,
    defense: 10,
    speed: 2.5,
    experience: 60,
    lootTable: [
      { itemId: 'gold_coin', chance: 1, minQuantity: 10, maxQuantity: 35 },
      { itemId: 'health_potion_medium', chance: 0.2, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'mana_potion_medium', chance: 0.15, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'iron_helmet', chance: 0.08, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#ecf0f1',
    icon: '💀',
    aggressive: true,
    chaseRange: 6,
    attackRange: 1,
    attackSpeed: 1600,
  },
  demon: {
    id: 'demon',
    name: 'Demon',
    health: 500,
    maxHealth: 500,
    attack: 60,
    defense: 35,
    speed: 3.5,
    experience: 300,
    lootTable: [
      { itemId: 'gold_coin', chance: 1, minQuantity: 50, maxQuantity: 200 },
      { itemId: 'health_potion_large', chance: 0.5, minQuantity: 1, maxQuantity: 3 },
      { itemId: 'mana_potion_large', chance: 0.4, minQuantity: 1, maxQuantity: 3 },
      { itemId: 'dragon_sword', chance: 0.05, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'plate_armor', chance: 0.08, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'tower_shield', chance: 0.05, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'crown_helmet', chance: 0.03, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'ring_of_life', chance: 0.1, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#c0392b',
    icon: '😈',
    aggressive: true,
    chaseRange: 12,
    attackRange: 2,
    attackSpeed: 2000,
  },
  dragon: {
    id: 'dragon',
    name: 'Dragon',
    health: 800,
    maxHealth: 800,
    attack: 80,
    defense: 50,
    speed: 3,
    experience: 500,
    lootTable: [
      { itemId: 'gold_coin', chance: 1, minQuantity: 100, maxQuantity: 500 },
      { itemId: 'health_potion_large', chance: 0.7, minQuantity: 2, maxQuantity: 5 },
      { itemId: 'mana_potion_large', chance: 0.5, minQuantity: 1, maxQuantity: 3 },
      { itemId: 'dragon_sword', chance: 0.1, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'plate_armor', chance: 0.15, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'tower_shield', chance: 0.1, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'crown_helmet', chance: 0.08, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#e74c3c',
    icon: '🐉',
    aggressive: true,
    chaseRange: 15,
    attackRange: 3,
    attackSpeed: 2500,
  },
};

export function getMonster(id: string): MonsterDefinition | undefined {
  return MONSTERS[id];
}