// =============================================
// Tibia-Style Game - Monster Definitions
// =============================================

import { MonsterDefinition } from './types';

export const MONSTERS: Record<string, MonsterDefinition> = {
  // === EASY (Forest) ===
  rat: {
    id: 'rat',
    name: 'Rat',
    health: 15,
    maxHealth: 15,
    attack: 6,
    defense: 1,
    speed: 2,
    experience: 10,
    lootTable: [
      { itemId: 'gold_coin', chance: 0.8, minQuantity: 1, maxQuantity: 5 },
      { itemId: 'health_potion_small', chance: 0.1, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#8B7355',
    icon: '🐀',
    aggressive: false,
    chaseRange: 3,
    attackRange: 1,
    attackSpeed: 2000,
    sprites: {
      north: '/sprites/rat/north.png', south: '/sprites/rat/south.png',
      east: '/sprites/rat/east.png', west: '/sprites/rat/west.png',
    },
  },
  bat: {
    id: 'bat',
    name: 'Cave Bat',
    health: 20,
    maxHealth: 20,
    attack: 10,
    defense: 2,
    speed: 4,
    experience: 15,
    lootTable: [
      { itemId: 'gold_coin', chance: 0.7, minQuantity: 1, maxQuantity: 8 },
      { itemId: 'mana_potion_small', chance: 0.12, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#4a235a',
    icon: '🦇',
    aggressive: false,
    chaseRange: 4,
    attackRange: 1,
    attackSpeed: 1500,
  },
  snake: {
    id: 'snake',
    name: 'Snake',
    health: 25,
    maxHealth: 25,
    attack: 16,
    defense: 2,
    speed: 3,
    experience: 20,
    lootTable: [
      { itemId: 'gold_coin', chance: 0.9, minQuantity: 2, maxQuantity: 10 },
      { itemId: 'health_potion_small', chance: 0.15, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'mana_potion_small', chance: 0.1, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#2ecc71',
    icon: '🐍',
    aggressive: true,
    chaseRange: 5,
    attackRange: 1,
    attackSpeed: 1500,
    sprites: {
      north: '/sprites/snake/north.png', south: '/sprites/snake/south.png',
      east: '/sprites/snake/east.png', west: '/sprites/snake/west.png',
    },
  },

  // === MEDIUM (Forest/Desert) ===
  spider: {
    id: 'spider',
    name: 'Giant Spider',
    health: 40,
    maxHealth: 40,
    attack: 24,
    defense: 5,
    speed: 3.5,
    experience: 35,
    lootTable: [
      { itemId: 'gold_coin', chance: 1, minQuantity: 5, maxQuantity: 20 },
      { itemId: 'health_potion_small', chance: 0.2, minQuantity: 1, maxQuantity: 2 },
      { itemId: 'leather_armor', chance: 0.05, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#2c3e50',
    icon: '🕷️',
    aggressive: true,
    chaseRange: 6,
    attackRange: 1,
    attackSpeed: 1200,
    sprites: {
      north: '/sprites/spider/north.png', south: '/sprites/spider/south.png',
      east: '/sprites/spider/east.png', west: '/sprites/spider/west.png',
    },
  },
  goblin: {
    id: 'goblin',
    name: 'Goblin',
    health: 55,
    maxHealth: 55,
    attack: 28,
    defense: 6,
    speed: 4,
    experience: 45,
    lootTable: [
      { itemId: 'gold_coin', chance: 1, minQuantity: 8, maxQuantity: 25 },
      { itemId: 'health_potion_small', chance: 0.25, minQuantity: 1, maxQuantity: 2 },
      { itemId: 'short_sword', chance: 0.08, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'wooden_shield', chance: 0.08, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'leather_helmet', chance: 0.06, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#27ae60',
    icon: '👺',
    aggressive: true,
    chaseRange: 6,
    attackRange: 1,
    attackSpeed: 1400,
  },
  wolf: {
    id: 'wolf',
    name: 'Wolf',
    health: 60,
    maxHealth: 60,
    attack: 36,
    defense: 8,
    speed: 4.5,
    experience: 50,
    lootTable: [
      { itemId: 'gold_coin', chance: 1, minQuantity: 8, maxQuantity: 30 },
      { itemId: 'health_potion_medium', chance: 0.15, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'leather_helmet', chance: 0.08, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'leather_legs', chance: 0.08, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#7f8c8d',
    icon: '🐺',
    aggressive: true,
    chaseRange: 7,
    attackRange: 1,
    attackSpeed: 1500,
    sprites: {
      north: '/sprites/wolf/north.png?v=2',
      south: '/sprites/wolf/south.png?v=2',
      east: '/sprites/wolf/east.png?v=2',
      west: '/sprites/wolf/west.png?v=2',
    },
  },
  scorpion: {
    id: 'scorpion',
    name: 'Giant Scorpion',
    health: 80,
    maxHealth: 80,
    attack: 44,
    defense: 12,
    speed: 3,
    experience: 60,
    lootTable: [
      { itemId: 'gold_coin', chance: 1, minQuantity: 10, maxQuantity: 35 },
      { itemId: 'health_potion_medium', chance: 0.2, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'chain_mail', chance: 0.04, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'iron_shield', chance: 0.04, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#d35400',
    icon: '🦂',
    aggressive: true,
    chaseRange: 5,
    attackRange: 1,
    attackSpeed: 1800,
  },

  // === MEDIUM-HARD ===
  orc: {
    id: 'orc',
    name: 'Orc',
    health: 120,
    maxHealth: 120,
    attack: 50,
    defense: 15,
    speed: 3,
    experience: 80,
    lootTable: [
      { itemId: 'gold_coin', chance: 1, minQuantity: 15, maxQuantity: 50 },
      { itemId: 'health_potion_medium', chance: 0.25, minQuantity: 1, maxQuantity: 2 },
      { itemId: 'short_sword', chance: 0.1, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'chain_mail', chance: 0.05, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'iron_shield', chance: 0.05, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#27ae60',
    icon: '👹',
    aggressive: true,
    chaseRange: 8,
    attackRange: 1,
    attackSpeed: 1800,
    sprites: {
      north: '/sprites/orc/north.png', south: '/sprites/orc/south.png',
      east: '/sprites/orc/east.png', west: '/sprites/orc/west.png',
    },
  },
  troll: {
    id: 'troll',
    name: 'Troll',
    health: 180,
    maxHealth: 180,
    attack: 60,
    defense: 18,
    speed: 2.5,
    experience: 100,
    lootTable: [
      { itemId: 'gold_coin', chance: 1, minQuantity: 20, maxQuantity: 60 },
      { itemId: 'health_potion_medium', chance: 0.3, minQuantity: 1, maxQuantity: 2 },
      { itemId: 'long_sword', chance: 0.08, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'battle_axe', chance: 0.05, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'chain_mail', chance: 0.08, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'chain_legs', chance: 0.08, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#6d4c2a',
    icon: '🧌',
    aggressive: true,
    chaseRange: 8,
    attackRange: 1,
    attackSpeed: 2000,
  },
  skeleton: {
    id: 'skeleton',
    name: 'Skeleton',
    health: 80,
    maxHealth: 80,
    attack: 40,
    defense: 10,
    speed: 2.5,
    experience: 60,
    lootTable: [
      { itemId: 'gold_coin', chance: 1, minQuantity: 10, maxQuantity: 35 },
      { itemId: 'health_potion_medium', chance: 0.2, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'mana_potion_medium', chance: 0.15, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'iron_helmet', chance: 0.08, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#ecf0f1',
    icon: '💀',
    aggressive: true,
    chaseRange: 6,
    attackRange: 1,
    attackSpeed: 1600,
    sprites: {
      north: '/sprites/skeleton/north.png', south: '/sprites/skeleton/south.png',
      east: '/sprites/skeleton/east.png', west: '/sprites/skeleton/west.png',
    },
  },
  wraith: {
    id: 'wraith',
    name: 'Wraith',
    health: 150,
    maxHealth: 150,
    attack: 70,
    defense: 10,
    speed: 3.5,
    experience: 120,
    lootTable: [
      { itemId: 'gold_coin', chance: 1, minQuantity: 25, maxQuantity: 70 },
      { itemId: 'mana_potion_medium', chance: 0.3, minQuantity: 1, maxQuantity: 2 },
      { itemId: 'mana_potion_large', chance: 0.1, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'ring_of_mana', chance: 0.05, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'mage_robe', chance: 0.08, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#8e44ad',
    icon: '👻',
    aggressive: true,
    chaseRange: 10,
    attackRange: 3,
    attackSpeed: 2000,
  },

  // === HARD (Cave) ===
  dark_mage: {
    id: 'dark_mage',
    name: 'Dark Mage',
    health: 200,
    maxHealth: 200,
    attack: 90,
    defense: 20,
    speed: 3,
    experience: 180,
    lootTable: [
      { itemId: 'gold_coin', chance: 1, minQuantity: 30, maxQuantity: 100 },
      { itemId: 'mana_potion_large', chance: 0.3, minQuantity: 1, maxQuantity: 2 },
      { itemId: 'health_potion_large', chance: 0.2, minQuantity: 1, maxQuantity: 2 },
      { itemId: 'arcane_staff', chance: 0.08, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'mage_robe', chance: 0.12, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'ring_of_mana', chance: 0.1, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#4a235a',
    icon: '🧙‍♂️',
    aggressive: true,
    chaseRange: 10,
    attackRange: 4,
    attackSpeed: 2500,
  },
  fire_elemental: {
    id: 'fire_elemental',
    name: 'Fire Elemental',
    health: 250,
    maxHealth: 250,
    attack: 100,
    defense: 25,
    speed: 3.5,
    experience: 200,
    lootTable: [
      { itemId: 'gold_coin', chance: 1, minQuantity: 35, maxQuantity: 120 },
      { itemId: 'health_potion_large', chance: 0.35, minQuantity: 1, maxQuantity: 3 },
      { itemId: 'mana_potion_large', chance: 0.25, minQuantity: 1, maxQuantity: 2 },
      { itemId: 'plate_armor', chance: 0.08, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'ring_of_life', chance: 0.08, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#e74c3c',
    icon: '🔥',
    aggressive: true,
    chaseRange: 12,
    attackRange: 2,
    attackSpeed: 1500,
  },

  // === BOSS ===
  demon: {
    id: 'demon',
    name: 'Demon',
    health: 500,
    maxHealth: 500,
    attack: 120,
    defense: 35,
    speed: 3.5,
    experience: 300,
    lootTable: [
      { itemId: 'gold_coin', chance: 1, minQuantity: 50, maxQuantity: 200 },
      { itemId: 'health_potion_large', chance: 0.5, minQuantity: 1, maxQuantity: 3 },
      { itemId: 'mana_potion_large', chance: 0.4, minQuantity: 1, maxQuantity: 3 },
      { itemId: 'dragon_sword', chance: 0.05, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'plate_armor', chance: 0.08, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'tower_shield', chance: 0.05, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'crown_helmet', chance: 0.03, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'ring_of_life', chance: 0.1, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#c0392b',
    icon: '😈',
    aggressive: true,
    chaseRange: 12,
    attackRange: 2,
    attackSpeed: 2000,
    sprites: {
      north: '/sprites/demon/north.png', south: '/sprites/demon/south.png',
      east: '/sprites/demon/east.png', west: '/sprites/demon/west.png',
    },
  },

  // === LEGENDARY ===
  dragon: {
    id: 'dragon',
    name: 'Dragon',
    health: 800,
    maxHealth: 800,
    attack: 160,
    defense: 50,
    speed: 3,
    experience: 500,
    lootTable: [
      { itemId: 'gold_coin', chance: 1, minQuantity: 100, maxQuantity: 500 },
      { itemId: 'health_potion_large', chance: 0.7, minQuantity: 2, maxQuantity: 5 },
      { itemId: 'mana_potion_large', chance: 0.5, minQuantity: 1, maxQuantity: 3 },
      { itemId: 'dragon_sword', chance: 0.1, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'plate_armor', chance: 0.15, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'tower_shield', chance: 0.1, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'crown_helmet', chance: 0.08, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#e74c3c',
    icon: '🐉',
    aggressive: true,
    chaseRange: 15,
    attackRange: 3,
    attackSpeed: 2500,
    sprites: {
      north: '/sprites/dragon/north.png', south: '/sprites/dragon/south.png',
      east: '/sprites/dragon/east.png', west: '/sprites/dragon/west.png',
    },
  },
  demon_lord: {
    id: 'demon_lord',
    name: 'Demon Lord',
    health: 1500,
    maxHealth: 1500,
    attack: 200,
    defense: 60,
    speed: 3.5,
    experience: 1000,
    lootTable: [
      { itemId: 'gold_coin', chance: 1, minQuantity: 200, maxQuantity: 800 },
      { itemId: 'health_potion_large', chance: 0.9, minQuantity: 3, maxQuantity: 8 },
      { itemId: 'mana_potion_large', chance: 0.8, minQuantity: 3, maxQuantity: 6 },
      { itemId: 'dragon_sword', chance: 0.2, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'inferno_staff', chance: 0.15, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'plate_armor', chance: 0.2, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'tower_shield', chance: 0.15, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'crown_helmet', chance: 0.15, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'ring_of_life', chance: 0.2, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'ring_of_mana', chance: 0.2, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#8e0000',
    icon: '👿',
    aggressive: true,
    chaseRange: 20,
    attackRange: 3,
    attackSpeed: 2000,
  },
  ancient_dragon: {
    id: 'ancient_dragon',
    name: 'Ancient Dragon',
    health: 2500,
    maxHealth: 2500,
    attack: 240,
    defense: 70,
    speed: 2.5,
    experience: 2000,
    lootTable: [
      { itemId: 'gold_coin', chance: 1, minQuantity: 500, maxQuantity: 1500 },
      { itemId: 'health_potion_large', chance: 1, minQuantity: 5, maxQuantity: 10 },
      { itemId: 'mana_potion_large', chance: 0.9, minQuantity: 5, maxQuantity: 8 },
      { itemId: 'dragon_sword', chance: 0.3, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'inferno_staff', chance: 0.25, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'plate_armor', chance: 0.3, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'tower_shield', chance: 0.2, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'crown_helmet', chance: 0.25, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'ring_of_life', chance: 0.3, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'ring_of_mana', chance: 0.3, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#922b21',
    icon: '🐲',
    aggressive: true,
    chaseRange: 25,
    attackRange: 4,
    attackSpeed: 2200,
  },

  // === NEW EASY ===
  rabbit: {
    id: 'rabbit',
    name: 'Rabbit',
    health: 8,
    maxHealth: 8,
    attack: 2,
    defense: 0,
    speed: 5,
    experience: 5,
    lootTable: [
      { itemId: 'gold_coin', chance: 0.5, minQuantity: 1, maxQuantity: 3 },
    ],
    color: '#f5f5dc',
    icon: '🐰',
    aggressive: false,
    chaseRange: 2,
    attackRange: 1,
    attackSpeed: 1500,
  },
  bee: {
    id: 'bee',
    name: 'Giant Bee',
    health: 12,
    maxHealth: 12,
    attack: 8,
    defense: 1,
    speed: 6,
    experience: 8,
    lootTable: [
      { itemId: 'gold_coin', chance: 0.6, minQuantity: 1, maxQuantity: 5 },
      { itemId: 'mana_potion_small', chance: 0.08, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#f1c40f',
    icon: '🐝',
    aggressive: false,
    chaseRange: 4,
    attackRange: 1,
    attackSpeed: 1000,
  },

  // === NEW MEDIUM ===
  bandit: {
    id: 'bandit',
    name: 'Bandit',
    health: 70,
    maxHealth: 70,
    attack: 32,
    defense: 7,
    speed: 3.5,
    experience: 55,
    lootTable: [
      { itemId: 'gold_coin', chance: 1, minQuantity: 10, maxQuantity: 30 },
      { itemId: 'health_potion_small', chance: 0.2, minQuantity: 1, maxQuantity: 2 },
      { itemId: 'short_sword', chance: 0.1, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#2c3e50',
    icon: '🗡️',
    aggressive: true,
    chaseRange: 7,
    attackRange: 1,
    attackSpeed: 1300,
  },
  boar: {
    id: 'boar',
    name: 'Wild Boar',
    health: 90,
    maxHealth: 90,
    attack: 40,
    defense: 10,
    speed: 4,
    experience: 55,
    lootTable: [
      { itemId: 'gold_coin', chance: 1, minQuantity: 8, maxQuantity: 25 },
      { itemId: 'leather_armor', chance: 0.08, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#8B4513',
    icon: '🐗',
    aggressive: true,
    chaseRange: 6,
    attackRange: 1,
    attackSpeed: 1400,
  },
  pirate: {
    id: 'pirate',
    name: 'Pirate',
    health: 100,
    maxHealth: 100,
    attack: 44,
    defense: 12,
    speed: 3,
    experience: 70,
    lootTable: [
      { itemId: 'gold_coin', chance: 1, minQuantity: 15, maxQuantity: 40 },
      { itemId: 'long_sword', chance: 0.08, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'chain_mail', chance: 0.06, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#1a5276',
    icon: '🏴‍☠️',
    aggressive: true,
    chaseRange: 8,
    attackRange: 1,
    attackSpeed: 1600,
  },
  mushroom: {
    id: 'mushroom',
    name: 'Poison Mushroom',
    health: 35,
    maxHealth: 35,
    attack: 30,
    defense: 3,
    speed: 1.5,
    experience: 30,
    lootTable: [
      { itemId: 'gold_coin', chance: 0.8, minQuantity: 5, maxQuantity: 15 },
      { itemId: 'mana_potion_small', chance: 0.2, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'mana_potion_medium', chance: 0.05, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#6c3483',
    icon: '🍄',
    aggressive: false,
    chaseRange: 3,
    attackRange: 1,
    attackSpeed: 2000,
  },

  // === NEW HARD ===
  golem: {
    id: 'golem',
    name: 'Stone Golem',
    health: 300,
    maxHealth: 300,
    attack: 80,
    defense: 35,
    speed: 1.5,
    experience: 150,
    lootTable: [
      { itemId: 'gold_coin', chance: 1, minQuantity: 30, maxQuantity: 80 },
      { itemId: 'iron_shield', chance: 0.1, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'steel_boots', chance: 0.08, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'plate_armor', chance: 0.05, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#7f8c8d',
    icon: '🗿',
    aggressive: false,
    chaseRange: 4,
    attackRange: 1,
    attackSpeed: 2500,
  },
  vampire: {
    id: 'vampire',
    name: 'Vampire',
    health: 200,
    maxHealth: 200,
    attack: 90,
    defense: 15,
    speed: 5,
    experience: 160,
    lootTable: [
      { itemId: 'gold_coin', chance: 1, minQuantity: 30, maxQuantity: 90 },
      { itemId: 'health_potion_large', chance: 0.15, minQuantity: 1, maxQuantity: 2 },
      { itemId: 'ring_of_life', chance: 0.08, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#c0392b',
    icon: '🧛',
    aggressive: true,
    chaseRange: 12,
    attackRange: 1,
    attackSpeed: 1200,
  },
  necromancer: {
    id: 'necromancer',
    name: 'Necromancer',
    health: 180,
    maxHealth: 180,
    attack: 110,
    defense: 18,
    speed: 2.5,
    experience: 200,
    lootTable: [
      { itemId: 'gold_coin', chance: 1, minQuantity: 40, maxQuantity: 120 },
      { itemId: 'arcane_staff', chance: 0.12, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'mystic_robe', chance: 0.1, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'ring_of_mana', chance: 0.12, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#1a1a2e',
    icon: '💀',
    aggressive: true,
    chaseRange: 10,
    attackRange: 5,
    attackSpeed: 2200,
  },
  hydra: {
    id: 'hydra',
    name: 'Hydra',
    health: 400,
    maxHealth: 400,
    attack: 110,
    defense: 30,
    speed: 3,
    experience: 250,
    lootTable: [
      { itemId: 'gold_coin', chance: 1, minQuantity: 50, maxQuantity: 150 },
      { itemId: 'health_potion_large', chance: 0.3, minQuantity: 1, maxQuantity: 3 },
      { itemId: 'plate_armor', chance: 0.1, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'dragon_sword', chance: 0.06, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#1e8449',
    icon: '🐍',
    aggressive: true,
    chaseRange: 10,
    attackRange: 2,
    attackSpeed: 1800,
  },
  phoenix: {
    id: 'phoenix',
    name: 'Phoenix',
    health: 350,
    maxHealth: 350,
    attack: 130,
    defense: 20,
    speed: 4.5,
    experience: 280,
    lootTable: [
      { itemId: 'gold_coin', chance: 1, minQuantity: 60, maxQuantity: 200 },
      { itemId: 'inferno_staff', chance: 0.1, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'enchanted_boots', chance: 0.15, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'mana_potion_large', chance: 0.4, minQuantity: 1, maxQuantity: 3 },
    ],
    color: '#e67e22',
    icon: '🦅',
    aggressive: true,
    chaseRange: 14,
    attackRange: 3,
    attackSpeed: 1500,
  },

  // === NEW BOSS / LEGENDARY ===
  lich_king: {
    id: 'lich_king',
    name: 'Lich King',
    health: 2000,
    maxHealth: 2000,
    attack: 200,
    defense: 50,
    speed: 3,
    experience: 1500,
    lootTable: [
      { itemId: 'gold_coin', chance: 1, minQuantity: 500, maxQuantity: 2000 },
      { itemId: 'arcane_staff', chance: 0.3, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'inferno_staff', chance: 0.2, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'mystic_robe', chance: 0.25, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'ring_of_mana', chance: 0.3, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'ring_of_life', chance: 0.2, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'crown_helmet', chance: 0.15, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#0d0d2b',
    icon: '👑',
    aggressive: true,
    chaseRange: 25,
    attackRange: 5,
    attackSpeed: 2000,
  },
  kraken: {
    id: 'kraken',
    name: 'Kraken',
    health: 3000,
    maxHealth: 3000,
    attack: 260,
    defense: 60,
    speed: 2,
    experience: 2500,
    lootTable: [
      { itemId: 'gold_coin', chance: 1, minQuantity: 800, maxQuantity: 3000 },
      { itemId: 'dragon_sword', chance: 0.25, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'inferno_staff', chance: 0.25, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'plate_armor', chance: 0.3, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'tower_shield', chance: 0.25, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'crown_helmet', chance: 0.2, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'ring_of_life', chance: 0.3, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#1b4f72',
    icon: '🐙',
    aggressive: true,
    chaseRange: 30,
    attackRange: 5,
    attackSpeed: 2500,
  },

  // === NEW ANIMALS ===
  deer: {
    id: 'deer', name: 'Deer', health: 35, maxHealth: 35, attack: 10, defense: 3, speed: 6, experience: 25,
    lootTable: [
      { itemId: 'gold_coin', chance: 0.6, minQuantity: 2, maxQuantity: 8 },
      { itemId: 'raw_meat', chance: 0.4, minQuantity: 1, maxQuantity: 2 },
    ],
    color: '#A0522D', icon: '🦌', aggressive: false, chaseRange: 6, attackRange: 1, attackSpeed: 1800,
  },
  bear: {
    id: 'bear', name: 'Brown Bear', health: 200, maxHealth: 200, attack: 70, defense: 20, speed: 3, experience: 120,
    lootTable: [
      { itemId: 'gold_coin', chance: 1, minQuantity: 20, maxQuantity: 60 },
      { itemId: 'health_potion_medium', chance: 0.25, minQuantity: 1, maxQuantity: 2 },
      { itemId: 'raw_meat', chance: 0.5, minQuantity: 2, maxQuantity: 4 },
      { itemId: 'bear_pelt', chance: 0.15, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#5C3317', icon: '🐻', aggressive: true, chaseRange: 8, attackRange: 1, attackSpeed: 1800,
    sprites: {
      north: '/sprites/bear/north.png', south: '/sprites/bear/south.png',
      east: '/sprites/bear/east.png', west: '/sprites/bear/west.png',
    },
  },
  crocodile: {
    id: 'crocodile', name: 'Crocodile', health: 150, maxHealth: 150, attack: 60, defense: 18, speed: 2.5, experience: 90,
    lootTable: [
      { itemId: 'gold_coin', chance: 1, minQuantity: 15, maxQuantity: 50 },
      { itemId: 'health_potion_medium', chance: 0.2, minQuantity: 1, maxQuantity: 2 },
      { itemId: 'crocodile_skin', chance: 0.12, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#2E5A1E', icon: '🐊', aggressive: true, chaseRange: 5, attackRange: 1, attackSpeed: 2000,
  },
  frog: {
    id: 'frog', name: 'Giant Frog', health: 20, maxHealth: 20, attack: 12, defense: 2, speed: 4, experience: 12,
    lootTable: [
      { itemId: 'gold_coin', chance: 0.5, minQuantity: 1, maxQuantity: 5 },
    ],
    color: '#228B22', icon: '🐸', aggressive: false, chaseRange: 3, attackRange: 1, attackSpeed: 1200,
  },
  hawk: {
    id: 'hawk', name: 'Hawk', health: 45, maxHealth: 45, attack: 30, defense: 5, speed: 5.5, experience: 35,
    lootTable: [
      { itemId: 'gold_coin', chance: 0.8, minQuantity: 5, maxQuantity: 15 },
      { itemId: 'feather', chance: 0.3, minQuantity: 1, maxQuantity: 3 },
    ],
    color: '#4A3520', icon: '🦅', aggressive: true, chaseRange: 10, attackRange: 1, attackSpeed: 1000,
  },
  crab: {
    id: 'crab', name: 'Giant Crab', health: 40, maxHealth: 40, attack: 28, defense: 15, speed: 2, experience: 30,
    lootTable: [
      { itemId: 'gold_coin', chance: 0.8, minQuantity: 3, maxQuantity: 12 },
      { itemId: 'crab_claw', chance: 0.2, minQuantity: 1, maxQuantity: 2 },
    ],
    color: '#B22222', icon: '🦀', aggressive: true, chaseRange: 3, attackRange: 1, attackSpeed: 1800,
  },
  minotaur: {
    id: 'minotaur', name: 'Minotaur', health: 350, maxHealth: 350, attack: 100, defense: 30, speed: 3, experience: 220,
    lootTable: [
      { itemId: 'gold_coin', chance: 1, minQuantity: 40, maxQuantity: 120 },
      { itemId: 'health_potion_large', chance: 0.3, minQuantity: 1, maxQuantity: 3 },
      { itemId: 'battle_axe', chance: 0.1, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'plate_armor', chance: 0.06, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'minotaur_horn', chance: 0.15, minQuantity: 1, maxQuantity: 2 },
    ],
    color: '#6B3A1A', icon: '🐂', aggressive: true, chaseRange: 10, attackRange: 1, attackSpeed: 1600,
  },
  cobra: {
    id: 'cobra', name: 'King Cobra', health: 100, maxHealth: 100, attack: 56, defense: 8, speed: 4, experience: 75,
    lootTable: [
      { itemId: 'gold_coin', chance: 1, minQuantity: 12, maxQuantity: 40 },
      { itemId: 'health_potion_medium', chance: 0.2, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'snake_venom', chance: 0.15, minQuantity: 1, maxQuantity: 2 },
    ],
    color: '#1A4A0E', icon: '🐍', aggressive: true, chaseRange: 6, attackRange: 1, attackSpeed: 1200,
  },

  // === NEW BEASTS & CREATURES ===
  wild_dog: {
    id: 'wild_dog', name: 'Wild Dog', health: 35, maxHealth: 35, attack: 20, defense: 4, speed: 5, experience: 25,
    lootTable: [
      { itemId: 'gold_coin', chance: 0.7, minQuantity: 1, maxQuantity: 8 },
      { itemId: 'leather_helmet', chance: 0.05, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'raw_meat', chance: 0.3, minQuantity: 1, maxQuantity: 2 },
    ],
    color: '#8B6914', icon: '🐕', aggressive: true, chaseRange: 6, attackRange: 1, attackSpeed: 1500,
  },
  cat: {
    id: 'cat', name: 'Stray Cat', health: 8, maxHealth: 8, attack: 4, defense: 1, speed: 6, experience: 5,
    lootTable: [
      { itemId: 'gold_coin', chance: 0.2, minQuantity: 1, maxQuantity: 2 },
      { itemId: 'feather', chance: 0.05, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#FF8C00', icon: '🐱', aggressive: false, chaseRange: 2, attackRange: 1, attackSpeed: 2000,
  },
  toad: {
    id: 'toad', name: 'Giant Toad', health: 30, maxHealth: 30, attack: 12, defense: 3, speed: 2, experience: 15,
    lootTable: [
      { itemId: 'gold_coin', chance: 0.6, minQuantity: 1, maxQuantity: 6 },
      { itemId: 'mana_potion_small', chance: 0.15, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#2E8B57', icon: '🐸', aggressive: false, chaseRange: 2, attackRange: 1, attackSpeed: 2000,
  },
  mantis: {
    id: 'mantis', name: 'Giant Mantis', health: 45, maxHealth: 45, attack: 32, defense: 6, speed: 5, experience: 40,
    lootTable: [
      { itemId: 'gold_coin', chance: 0.8, minQuantity: 3, maxQuantity: 15 },
      { itemId: 'health_potion_small', chance: 0.2, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'feather', chance: 0.25, minQuantity: 1, maxQuantity: 3 },
    ],
    color: '#228B22', icon: '🦗', aggressive: true, chaseRange: 5, attackRange: 1, attackSpeed: 1200,
  },
  war_wolf: {
    id: 'war_wolf', name: 'War Wolf', health: 100, maxHealth: 100, attack: 56, defense: 12, speed: 5, experience: 75,
    lootTable: [
      { itemId: 'gold_coin', chance: 1, minQuantity: 10, maxQuantity: 35 },
      { itemId: 'health_potion_medium', chance: 0.2, minQuantity: 1, maxQuantity: 2 },
      { itemId: 'wolf_pelt_cloak', chance: 0.1, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'leather_armor', chance: 0.05, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'war_wolf_fang', chance: 0.25, minQuantity: 1, maxQuantity: 2 },
    ],
    color: '#2F2F2F', icon: '🐺', aggressive: true, chaseRange: 8, attackRange: 1, attackSpeed: 1400,
  },
  wild_boar: {
    id: 'wild_boar', name: 'Wild Boar', health: 70, maxHealth: 70, attack: 40, defense: 10, speed: 4, experience: 55,
    lootTable: [
      { itemId: 'gold_coin', chance: 0.9, minQuantity: 5, maxQuantity: 20 },
      { itemId: 'raw_meat', chance: 0.4, minQuantity: 1, maxQuantity: 3 },
      { itemId: 'leather_legs', chance: 0.08, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#5C4033', icon: '🐗', aggressive: true, chaseRange: 5, attackRange: 1, attackSpeed: 1600,
  },
  stone_golem: {
    id: 'stone_golem', name: 'Stone Golem', health: 300, maxHealth: 300, attack: 70, defense: 30, speed: 1.5, experience: 150,
    lootTable: [
      { itemId: 'gold_coin', chance: 1, minQuantity: 30, maxQuantity: 80 },
      { itemId: 'iron_shield', chance: 0.08, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'plate_armor', chance: 0.05, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'golem_core', chance: 0.15, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#696969', icon: '🗿', aggressive: false, chaseRange: 3, attackRange: 1, attackSpeed: 3000,
  },
  ghost: {
    id: 'ghost', name: 'Ghost', health: 50, maxHealth: 50, attack: 50, defense: 5, speed: 3, experience: 60,
    lootTable: [
      { itemId: 'gold_coin', chance: 0.8, minQuantity: 5, maxQuantity: 20 },
      { itemId: 'mana_potion_medium', chance: 0.2, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'amulet_of_wisdom', chance: 0.03, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'ghost_essence', chance: 0.3, minQuantity: 1, maxQuantity: 2 },
    ],
    color: '#B0C4DE', icon: '👻', aggressive: true, chaseRange: 7, attackRange: 1, attackSpeed: 1800,
  },
  thornback: {
    id: 'thornback', name: 'Thornback Tortoise', health: 120, maxHealth: 120, attack: 20, defense: 35, speed: 1.5, experience: 65,
    lootTable: [
      { itemId: 'gold_coin', chance: 1, minQuantity: 8, maxQuantity: 25 },
      { itemId: 'crocodile_skin', chance: 0.15, minQuantity: 1, maxQuantity: 2 },
      { itemId: 'health_potion_medium', chance: 0.15, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'tortoise_shell', chance: 0.3, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#556B2F', icon: '🐢', aggressive: false, chaseRange: 2, attackRange: 1, attackSpeed: 2500,
  },
  eagle: {
    id: 'eagle', name: 'Mountain Eagle', health: 55, maxHealth: 55, attack: 44, defense: 6, speed: 6, experience: 50,
    lootTable: [
      { itemId: 'gold_coin', chance: 0.9, minQuantity: 5, maxQuantity: 18 },
      { itemId: 'feather', chance: 0.5, minQuantity: 1, maxQuantity: 4 },
      { itemId: 'health_potion_small', chance: 0.15, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'eagle_talon', chance: 0.3, minQuantity: 1, maxQuantity: 2 },
    ],
    color: '#4A3728', icon: '🦅', aggressive: true, chaseRange: 8, attackRange: 1, attackSpeed: 1000,
  },
};

export function getMonster(id: string): MonsterDefinition | undefined {
  return MONSTERS[id];
}