// =============================================
// Tibia-Style Game - Monster Definitions
// =============================================

import { MonsterDefinition } from './types';

export const MONSTERS: Record<string, MonsterDefinition> = {
  // === EASY (Forest) ===
  rat: {
    id: 'rat',
    name: 'Rat',
    health: 15,
    maxHealth: 15,
    attack: 3,
    defense: 1,
    speed: 2,
    experience: 10,
    lootTable: [
      { itemId: 'gold_coin', chance: 0.8, minQuantity: 1, maxQuantity: 5 },
      { itemId: 'health_potion_small', chance: 0.1, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#8B7355',
    icon: '🐀',
    aggressive: false,
    chaseRange: 3,
    attackRange: 1,
    attackSpeed: 2000,
  },
  bat: {
    id: 'bat',
    name: 'Cave Bat',
    health: 20,
    maxHealth: 20,
    attack: 5,
    defense: 2,
    speed: 4,
    experience: 15,
    lootTable: [
      { itemId: 'gold_coin', chance: 0.7, minQuantity: 1, maxQuantity: 8 },
      { itemId: 'mana_potion_small', chance: 0.12, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#4a235a',
    icon: '🦇',
    aggressive: false,
    chaseRange: 4,
    attackRange: 1,
    attackSpeed: 1500,
  },
  snake: {
    id: 'snake',
    name: 'Snake',
    health: 25,
    maxHealth: 25,
    attack: 8,
    defense: 2,
    speed: 3,
    experience: 20,
    lootTable: [
      { itemId: 'gold_coin', chance: 0.9, minQuantity: 2, maxQuantity: 10 },
      { itemId: 'health_potion_small', chance: 0.15, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'mana_potion_small', chance: 0.1, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#2ecc71',
    icon: '🐍',
    aggressive: true,
    chaseRange: 5,
    attackRange: 1,
    attackSpeed: 1500,
  },

  // === MEDIUM (Forest/Desert) ===
  spider: {
    id: 'spider',
    name: 'Giant Spider',
    health: 40,
    maxHealth: 40,
    attack: 12,
    defense: 5,
    speed: 3.5,
    experience: 35,
    lootTable: [
      { itemId: 'gold_coin', chance: 1, minQuantity: 5, maxQuantity: 20 },
      { itemId: 'health_potion_small', chance: 0.2, minQuantity: 1, maxQuantity: 2 },
      { itemId: 'leather_armor', chance: 0.05, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#2c3e50',
    icon: '🕷️',
    aggressive: true,
    chaseRange: 6,
    attackRange: 1,
    attackSpeed: 1200,
  },
  goblin: {
    id: 'goblin',
    name: 'Goblin',
    health: 55,
    maxHealth: 55,
    attack: 14,
    defense: 6,
    speed: 4,
    experience: 45,
    lootTable: [
      { itemId: 'gold_coin', chance: 1, minQuantity: 8, maxQuantity: 25 },
      { itemId: 'health_potion_small', chance: 0.25, minQuantity: 1, maxQuantity: 2 },
      { itemId: 'short_sword', chance: 0.08, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'wooden_shield', chance: 0.08, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'leather_helmet', chance: 0.06, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#27ae60',
    icon: '👺',
    aggressive: true,
    chaseRange: 6,
    attackRange: 1,
    attackSpeed: 1400,
  },
  wolf: {
    id: 'wolf',
    name: 'Wolf',
    health: 60,
    maxHealth: 60,
    attack: 18,
    defense: 8,
    speed: 4.5,
    experience: 50,
    lootTable: [
      { itemId: 'gold_coin', chance: 1, minQuantity: 8, maxQuantity: 30 },
      { itemId: 'health_potion_medium', chance: 0.15, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'leather_helmet', chance: 0.08, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'leather_legs', chance: 0.08, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#7f8c8d',
    icon: '🐺',
    aggressive: true,
    chaseRange: 7,
    attackRange: 1,
    attackSpeed: 1500,
  },
  scorpion: {
    id: 'scorpion',
    name: 'Giant Scorpion',
    health: 80,
    maxHealth: 80,
    attack: 22,
    defense: 12,
    speed: 3,
    experience: 60,
    lootTable: [
      { itemId: 'gold_coin', chance: 1, minQuantity: 10, maxQuantity: 35 },
      { itemId: 'health_potion_medium', chance: 0.2, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'chain_mail', chance: 0.04, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'iron_shield', chance: 0.04, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#d35400',
    icon: '🦂',
    aggressive: true,
    chaseRange: 5,
    attackRange: 1,
    attackSpeed: 1800,
  },

  // === MEDIUM-HARD ===
  orc: {
    id: 'orc',
    name: 'Orc',
    health: 120,
    maxHealth: 120,
    attack: 25,
    defense: 15,
    speed: 3,
    experience: 80,
    lootTable: [
      { itemId: 'gold_coin', chance: 1, minQuantity: 15, maxQuantity: 50 },
      { itemId: 'health_potion_medium', chance: 0.25, minQuantity: 1, maxQuantity: 2 },
      { itemId: 'short_sword', chance: 0.1, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'chain_mail', chance: 0.05, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'iron_shield', chance: 0.05, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#27ae60',
    icon: '👹',
    aggressive: true,
    chaseRange: 8,
    attackRange: 1,
    attackSpeed: 1800,
  },
  troll: {
    id: 'troll',
    name: 'Troll',
    health: 180,
    maxHealth: 180,
    attack: 30,
    defense: 18,
    speed: 2.5,
    experience: 100,
    lootTable: [
      { itemId: 'gold_coin', chance: 1, minQuantity: 20, maxQuantity: 60 },
      { itemId: 'health_potion_medium', chance: 0.3, minQuantity: 1, maxQuantity: 2 },
      { itemId: 'long_sword', chance: 0.08, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'battle_axe', chance: 0.05, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'chain_mail', chance: 0.08, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'chain_legs', chance: 0.08, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#6d4c2a',
    icon: '🧌',
    aggressive: true,
    chaseRange: 8,
    attackRange: 1,
    attackSpeed: 2000,
  },
  skeleton: {
    id: 'skeleton',
    name: 'Skeleton',
    health: 80,
    maxHealth: 80,
    attack: 20,
    defense: 10,
    speed: 2.5,
    experience: 60,
    lootTable: [
      { itemId: 'gold_coin', chance: 1, minQuantity: 10, maxQuantity: 35 },
      { itemId: 'health_potion_medium', chance: 0.2, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'mana_potion_medium', chance: 0.15, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'iron_helmet', chance: 0.08, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#ecf0f1',
    icon: '💀',
    aggressive: true,
    chaseRange: 6,
    attackRange: 1,
    attackSpeed: 1600,
  },
  wraith: {
    id: 'wraith',
    name: 'Wraith',
    health: 150,
    maxHealth: 150,
    attack: 35,
    defense: 10,
    speed: 3.5,
    experience: 120,
    lootTable: [
      { itemId: 'gold_coin', chance: 1, minQuantity: 25, maxQuantity: 70 },
      { itemId: 'mana_potion_medium', chance: 0.3, minQuantity: 1, maxQuantity: 2 },
      { itemId: 'mana_potion_large', chance: 0.1, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'ring_of_mana', chance: 0.05, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'mage_robe', chance: 0.08, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#8e44ad',
    icon: '👻',
    aggressive: true,
    chaseRange: 10,
    attackRange: 3,
    attackSpeed: 2000,
  },

  // === HARD (Cave) ===
  dark_mage: {
    id: 'dark_mage',
    name: 'Dark Mage',
    health: 200,
    maxHealth: 200,
    attack: 45,
    defense: 20,
    speed: 3,
    experience: 180,
    lootTable: [
      { itemId: 'gold_coin', chance: 1, minQuantity: 30, maxQuantity: 100 },
      { itemId: 'mana_potion_large', chance: 0.3, minQuantity: 1, maxQuantity: 2 },
      { itemId: 'health_potion_large', chance: 0.2, minQuantity: 1, maxQuantity: 2 },
      { itemId: 'arcane_staff', chance: 0.08, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'mage_robe', chance: 0.12, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'ring_of_mana', chance: 0.1, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#4a235a',
    icon: '🧙‍♂️',
    aggressive: true,
    chaseRange: 10,
    attackRange: 4,
    attackSpeed: 2500,
  },
  fire_elemental: {
    id: 'fire_elemental',
    name: 'Fire Elemental',
    health: 250,
    maxHealth: 250,
    attack: 50,
    defense: 25,
    speed: 3.5,
    experience: 200,
    lootTable: [
      { itemId: 'gold_coin', chance: 1, minQuantity: 35, maxQuantity: 120 },
      { itemId: 'health_potion_large', chance: 0.35, minQuantity: 1, maxQuantity: 3 },
      { itemId: 'mana_potion_large', chance: 0.25, minQuantity: 1, maxQuantity: 2 },
      { itemId: 'plate_armor', chance: 0.08, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'ring_of_life', chance: 0.08, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#e74c3c',
    icon: '🔥',
    aggressive: true,
    chaseRange: 12,
    attackRange: 2,
    attackSpeed: 1500,
  },

  // === BOSS ===
  demon: {
    id: 'demon',
    name: 'Demon',
    health: 500,
    maxHealth: 500,
    attack: 60,
    defense: 35,
    speed: 3.5,
    experience: 300,
    lootTable: [
      { itemId: 'gold_coin', chance: 1, minQuantity: 50, maxQuantity: 200 },
      { itemId: 'health_potion_large', chance: 0.5, minQuantity: 1, maxQuantity: 3 },
      { itemId: 'mana_potion_large', chance: 0.4, minQuantity: 1, maxQuantity: 3 },
      { itemId: 'dragon_sword', chance: 0.05, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'plate_armor', chance: 0.08, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'tower_shield', chance: 0.05, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'crown_helmet', chance: 0.03, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'ring_of_life', chance: 0.1, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#c0392b',
    icon: '😈',
    aggressive: true,
    chaseRange: 12,
    attackRange: 2,
    attackSpeed: 2000,
  },

  // === LEGENDARY ===
  dragon: {
    id: 'dragon',
    name: 'Dragon',
    health: 800,
    maxHealth: 800,
    attack: 80,
    defense: 50,
    speed: 3,
    experience: 500,
    lootTable: [
      { itemId: 'gold_coin', chance: 1, minQuantity: 100, maxQuantity: 500 },
      { itemId: 'health_potion_large', chance: 0.7, minQuantity: 2, maxQuantity: 5 },
      { itemId: 'mana_potion_large', chance: 0.5, minQuantity: 1, maxQuantity: 3 },
      { itemId: 'dragon_sword', chance: 0.1, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'plate_armor', chance: 0.15, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'tower_shield', chance: 0.1, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'crown_helmet', chance: 0.08, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#e74c3c',
    icon: '🐉',
    aggressive: true,
    chaseRange: 15,
    attackRange: 3,
    attackSpeed: 2500,
  },
  demon_lord: {
    id: 'demon_lord',
    name: 'Demon Lord',
    health: 1500,
    maxHealth: 1500,
    attack: 100,
    defense: 60,
    speed: 3.5,
    experience: 1000,
    lootTable: [
      { itemId: 'gold_coin', chance: 1, minQuantity: 200, maxQuantity: 800 },
      { itemId: 'health_potion_large', chance: 0.9, minQuantity: 3, maxQuantity: 8 },
      { itemId: 'mana_potion_large', chance: 0.8, minQuantity: 3, maxQuantity: 6 },
      { itemId: 'dragon_sword', chance: 0.2, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'inferno_staff', chance: 0.15, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'plate_armor', chance: 0.2, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'tower_shield', chance: 0.15, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'crown_helmet', chance: 0.15, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'ring_of_life', chance: 0.2, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'ring_of_mana', chance: 0.2, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#8e0000',
    icon: '👿',
    aggressive: true,
    chaseRange: 20,
    attackRange: 3,
    attackSpeed: 2000,
  },
  ancient_dragon: {
    id: 'ancient_dragon',
    name: 'Ancient Dragon',
    health: 2500,
    maxHealth: 2500,
    attack: 120,
    defense: 70,
    speed: 2.5,
    experience: 2000,
    lootTable: [
      { itemId: 'gold_coin', chance: 1, minQuantity: 500, maxQuantity: 1500 },
      { itemId: 'health_potion_large', chance: 1, minQuantity: 5, maxQuantity: 10 },
      { itemId: 'mana_potion_large', chance: 0.9, minQuantity: 5, maxQuantity: 8 },
      { itemId: 'dragon_sword', chance: 0.3, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'inferno_staff', chance: 0.25, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'plate_armor', chance: 0.3, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'tower_shield', chance: 0.2, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'crown_helmet', chance: 0.25, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'ring_of_life', chance: 0.3, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'ring_of_mana', chance: 0.3, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#922b21',
    icon: '🐲',
    aggressive: true,
    chaseRange: 25,
    attackRange: 4,
    attackSpeed: 2200,
  },

  // === NEW EASY ===
  rabbit: {
    id: 'rabbit',
    name: 'Rabbit',
    health: 8,
    maxHealth: 8,
    attack: 1,
    defense: 0,
    speed: 5,
    experience: 5,
    lootTable: [
      { itemId: 'gold_coin', chance: 0.5, minQuantity: 1, maxQuantity: 3 },
    ],
    color: '#f5f5dc',
    icon: '🐰',
    aggressive: false,
    chaseRange: 2,
    attackRange: 1,
    attackSpeed: 1500,
  },
  bee: {
    id: 'bee',
    name: 'Giant Bee',
    health: 12,
    maxHealth: 12,
    attack: 4,
    defense: 1,
    speed: 6,
    experience: 8,
    lootTable: [
      { itemId: 'gold_coin', chance: 0.6, minQuantity: 1, maxQuantity: 5 },
      { itemId: 'mana_potion_small', chance: 0.08, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#f1c40f',
    icon: '🐝',
    aggressive: false,
    chaseRange: 4,
    attackRange: 1,
    attackSpeed: 1000,
  },

  // === NEW MEDIUM ===
  bandit: {
    id: 'bandit',
    name: 'Bandit',
    health: 70,
    maxHealth: 70,
    attack: 16,
    defense: 7,
    speed: 3.5,
    experience: 55,
    lootTable: [
      { itemId: 'gold_coin', chance: 1, minQuantity: 10, maxQuantity: 30 },
      { itemId: 'health_potion_small', chance: 0.2, minQuantity: 1, maxQuantity: 2 },
      { itemId: 'short_sword', chance: 0.1, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#2c3e50',
    icon: '🗡️',
    aggressive: true,
    chaseRange: 7,
    attackRange: 1,
    attackSpeed: 1300,
  },
  boar: {
    id: 'boar',
    name: 'Wild Boar',
    health: 90,
    maxHealth: 90,
    attack: 20,
    defense: 10,
    speed: 4,
    experience: 55,
    lootTable: [
      { itemId: 'gold_coin', chance: 1, minQuantity: 8, maxQuantity: 25 },
      { itemId: 'leather_armor', chance: 0.08, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#8B4513',
    icon: '🐗',
    aggressive: true,
    chaseRange: 6,
    attackRange: 1,
    attackSpeed: 1400,
  },
  pirate: {
    id: 'pirate',
    name: 'Pirate',
    health: 100,
    maxHealth: 100,
    attack: 22,
    defense: 12,
    speed: 3,
    experience: 70,
    lootTable: [
      { itemId: 'gold_coin', chance: 1, minQuantity: 15, maxQuantity: 40 },
      { itemId: 'long_sword', chance: 0.08, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'chain_mail', chance: 0.06, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#1a5276',
    icon: '🏴‍☠️',
    aggressive: true,
    chaseRange: 8,
    attackRange: 1,
    attackSpeed: 1600,
  },
  mushroom: {
    id: 'mushroom',
    name: 'Poison Mushroom',
    health: 35,
    maxHealth: 35,
    attack: 15,
    defense: 3,
    speed: 1.5,
    experience: 30,
    lootTable: [
      { itemId: 'gold_coin', chance: 0.8, minQuantity: 5, maxQuantity: 15 },
      { itemId: 'mana_potion_small', chance: 0.2, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'mana_potion_medium', chance: 0.05, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#6c3483',
    icon: '🍄',
    aggressive: false,
    chaseRange: 3,
    attackRange: 1,
    attackSpeed: 2000,
  },

  // === NEW HARD ===
  golem: {
    id: 'golem',
    name: 'Stone Golem',
    health: 300,
    maxHealth: 300,
    attack: 40,
    defense: 35,
    speed: 1.5,
    experience: 150,
    lootTable: [
      { itemId: 'gold_coin', chance: 1, minQuantity: 30, maxQuantity: 80 },
      { itemId: 'iron_shield', chance: 0.1, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'steel_boots', chance: 0.08, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'plate_armor', chance: 0.05, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#7f8c8d',
    icon: '🗿',
    aggressive: false,
    chaseRange: 4,
    attackRange: 1,
    attackSpeed: 2500,
  },
  vampire: {
    id: 'vampire',
    name: 'Vampire',
    health: 200,
    maxHealth: 200,
    attack: 45,
    defense: 15,
    speed: 5,
    experience: 160,
    lootTable: [
      { itemId: 'gold_coin', chance: 1, minQuantity: 30, maxQuantity: 90 },
      { itemId: 'health_potion_large', chance: 0.15, minQuantity: 1, maxQuantity: 2 },
      { itemId: 'ring_of_life', chance: 0.08, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#c0392b',
    icon: '🧛',
    aggressive: true,
    chaseRange: 12,
    attackRange: 1,
    attackSpeed: 1200,
  },
  necromancer: {
    id: 'necromancer',
    name: 'Necromancer',
    health: 180,
    maxHealth: 180,
    attack: 55,
    defense: 18,
    speed: 2.5,
    experience: 200,
    lootTable: [
      { itemId: 'gold_coin', chance: 1, minQuantity: 40, maxQuantity: 120 },
      { itemId: 'arcane_staff', chance: 0.12, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'mystic_robe', chance: 0.1, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'ring_of_mana', chance: 0.12, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#1a1a2e',
    icon: '💀',
    aggressive: true,
    chaseRange: 10,
    attackRange: 5,
    attackSpeed: 2200,
  },
  hydra: {
    id: 'hydra',
    name: 'Hydra',
    health: 400,
    maxHealth: 400,
    attack: 55,
    defense: 30,
    speed: 3,
    experience: 250,
    lootTable: [
      { itemId: 'gold_coin', chance: 1, minQuantity: 50, maxQuantity: 150 },
      { itemId: 'health_potion_large', chance: 0.3, minQuantity: 1, maxQuantity: 3 },
      { itemId: 'plate_armor', chance: 0.1, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'dragon_sword', chance: 0.06, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#1e8449',
    icon: '🐍',
    aggressive: true,
    chaseRange: 10,
    attackRange: 2,
    attackSpeed: 1800,
  },
  phoenix: {
    id: 'phoenix',
    name: 'Phoenix',
    health: 350,
    maxHealth: 350,
    attack: 65,
    defense: 20,
    speed: 4.5,
    experience: 280,
    lootTable: [
      { itemId: 'gold_coin', chance: 1, minQuantity: 60, maxQuantity: 200 },
      { itemId: 'inferno_staff', chance: 0.1, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'enchanted_boots', chance: 0.15, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'mana_potion_large', chance: 0.4, minQuantity: 1, maxQuantity: 3 },
    ],
    color: '#e67e22',
    icon: '🦅',
    aggressive: true,
    chaseRange: 14,
    attackRange: 3,
    attackSpeed: 1500,
  },

  // === NEW BOSS / LEGENDARY ===
  lich_king: {
    id: 'lich_king',
    name: 'Lich King',
    health: 2000,
    maxHealth: 2000,
    attack: 100,
    defense: 50,
    speed: 3,
    experience: 1500,
    lootTable: [
      { itemId: 'gold_coin', chance: 1, minQuantity: 500, maxQuantity: 2000 },
      { itemId: 'arcane_staff', chance: 0.3, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'inferno_staff', chance: 0.2, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'mystic_robe', chance: 0.25, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'ring_of_mana', chance: 0.3, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'ring_of_life', chance: 0.2, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'crown_helmet', chance: 0.15, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#0d0d2b',
    icon: '👑',
    aggressive: true,
    chaseRange: 25,
    attackRange: 5,
    attackSpeed: 2000,
  },
  kraken: {
    id: 'kraken',
    name: 'Kraken',
    health: 3000,
    maxHealth: 3000,
    attack: 130,
    defense: 60,
    speed: 2,
    experience: 2500,
    lootTable: [
      { itemId: 'gold_coin', chance: 1, minQuantity: 800, maxQuantity: 3000 },
      { itemId: 'dragon_sword', chance: 0.25, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'inferno_staff', chance: 0.25, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'plate_armor', chance: 0.3, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'tower_shield', chance: 0.25, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'crown_helmet', chance: 0.2, minQuantity: 1, maxQuantity: 1 },
      { itemId: 'ring_of_life', chance: 0.3, minQuantity: 1, maxQuantity: 1 },
    ],
    color: '#1b4f72',
    icon: '🐙',
    aggressive: true,
    chaseRange: 30,
    attackRange: 5,
    attackSpeed: 2500,
  },
};

export function getMonster(id: string): MonsterDefinition | undefined {
  return MONSTERS[id];
}